mithril.js

Hey!
Just noticed this when I used google closure compiler for a project, for once:
```
mithril.js:21: WARNING - Parse error. Non-JSDoc comment has annotations. Did you mean to start it with '/**'?
/*
^
mithril.js:27: WARNING - Parse error. Non-JSDoc comment has annotations. Did you mean to start it with '/**'?
/*
^
0 error(s), 2 warning(s)
```
Seems that simply adding the extra `*` in the comments makes the compiler happy again. So this PR fixes that.
These lines are warnings of course, but seems like a quick win to fix. If the code blocks were formatted like that on purpose, and that this breaks something, please ignore.
```bash
npm i closure-compiler
java -jar node_modules/closure-compiler/lib/vendor/compiler.jar mithril.js > /dev/null
```
See above
No output
Thanks again for an …

Make code block comments the way closure compiler likes them.

---

package.json

Also, fixes name of grunt-jscs. grunt-jscs-checker has been renamed grunt-jscs, and npm was warning about that. Unfortunately, there are no versions of grunt-jscs below 0.6.0, so I upgraded to a current version.
This change does not seem to affect installation or the results of `grunt`.
Also, I removed duplicate keys from package.json.

Adds repository field to package.json.

---

mithril.js

requestAnimationFrame, setTimeout and clearTimeout need to be called on the window object explicitely in node-webkit.

fixes TypeError: Illegal Invocation in node-webkit

---

mithril.js

If rewriting the entire document with m.module it's possible that the body may change before any jsonp callbacks fire.  This PR makes sure to remove the script from the original body.
```
var App = {
controller: function() {
this.items = m.request({
method: 'GET',
dataType: 'jsonp',
url: '/items.json',
initialValue: [],
background: true
});
this.items.then(m.redraw);
},
view: function(ctrl) {
return m('html', [
m('head'[m('title', 'Items')]),
m('body', ctrl.items().map(function(item) { m('.item', item)}))
]);
}
};
m.module(document, App);
```

remove script from parentNode since $document.body may have changed

---

Gruntfile.js
docs/layout/package.json

Because Mithril looks so lost and forlorn on [npm](https://www.npmjs.com/package/mithril) without a readme.
README.* was added to the files section of the package.json
instead of README.md because a find/replace operation changes
.md to .html

README.md is now copied to the output and included for npm publish

---

mithril.js

The fix for #428 provided prevents entries beeing written to history. History.back() or hitting browsers back-button don't work anymore, since there are no history entries. 
This is because you are assigning the new path to route to to currentPath and compare these, which always turn out to be equal. Saving the currentPath before the assignment fixes this missbehaviour.

fix for #428 introduces new misbehaviour

---

mithril.js

I had some problems with the Haxe implementation in 0.1.29, and it turned out to be a new call syntax in redraw that caused it. When called as `(modules[i].view || blank)` the context for modules[i].view is lost, and `this` will be `window` in the view function. Calling `modules[i].view` directly fixes it.

Fixed context when calling a module view during redraw.

---

mithril.js
tests/mithril-tests.js

Many servers that support multiple arguments require that the url have  `[]` encode before the equal sign of a query parameter. Since this isn't a standard supported by all servers, I understand if you don't want to accept this change.

added multi argument brackets

---

mithril.js

Currently, it is close to impossible to read the status code of a response from a server using m.request. With this however, in failure cases, I can create a special wrapping for error cases, adding any detail from header or status code into the response.
This comes as a somewhat opposite of extract where instead we're extracting data from the xhr to deserialize, we are adding data from the xhr to the serialized data. This gives us the power to do something like this:
```javascript
var unwrap = function(data, xhr) {
return {
status: xhr.status,
text: xhr.statusText,
data: data
};
};
m.request({method: 'GET', url: apiUrl + path, unwrapError: unwrap });
```
With this, any failed request will have a standard format regardless of the message I get from the server. This is very handy when most …

m.request: Add XMLHttpRequest parameter to the unwrap method

---

mithril.d.ts

A small addition to the previous PR, with two changes:
- making it possible to also use TypeScript classes as controllers
- making indentation of .d.ts consistent with mithril.js (was 7 spaces, now 4)
Tests and demos are [here again](https://github.com/cbowdon/HeavyMithril). As always, let me know if you want me to make any changes and I'll be happy to.

Typescript stricter defs

---

mithril.js
tests/mithril-tests.js

chaining .then() after m.request() will now properly return initialValue if specified.
```javascript
var test = m.request({method: "GET", url: "package.json", background: true, initialValue: "test"}).then(function(d) { return d; });
test(); //will now return 'test' and not undefined.
```

propify: Fix chaining to return original m.prop

---

docs/tools.md

Before adding this sentence, the first paragraph required me to look up `Array::indexOf` and those other functions to see what versions of Internet Explorer they were first supported in. Now, the relevance of that list is clear.
I also fixed the capitalization of “ECMAScript”.

tools.md: explicitly say IE8 needs polyfills

---

docs/components.md

A few simple fixes to the Components docs:
- In "Aggregation of Responsibility" example, correctly access `contacts` from the controller
- Consistently use the name `args` for arguments passed to a module
- Add `ctrl` argument to views that were missing it
Note: I didn't bother adding semicolons because they seem to be consistently omitted; I assume this is intentional (?).

Component docs fixes

---

mithril.js

The `m.route.parseQueryString` method doesn't not correctly account for a `?` in a string, which is returned when calling `window.location.search`. It seems that Mithril should take this into account.

added parsing of '?' for query strings

---

mithril.js

Looks like you did a mass find/replace of ‘module’ to ‘component’,
accidentally breaking module.exports

Fix module.exports

---

mithril.js

onunload functions collected from components in `build()` weren't being called with the controller as their context.
```javascript
myComponent.controller = function() {
this.foo = 'bar';
this.onunload = function() {
console.log(this.foo); // expected: bar, actual: undefined
}
}
```

Fix onunload being called with incorrect context

---

mithril.js

Currently, `m.request({ method: 'get', data: foo, url: bar })` doesn't send the data to the server because the method is checked against uppercase `"GET"`. The documentation does say the 'method must be either `"GET"`, `"POST"`, ...', but it wasn't immediately obvious why it didn't work because HTTP methods are usually treated case-insensitively.

Canonicalize `options.method` in m.request

---

docs/mithril.request.md

Signature document for "background" option contains almost same meaning sentences. First one has more information, and I think separated warning message is easy to read (difficult to pass through), I changed like this:
* Remove a simpler sentence.
* Move a detailed sentence to the bottom where simpler sentence was originally.

Duplicated senteces

---

package.json

I added grunt as a devDependency to stop the many warnings like this
```
npm WARN peerDependencies The peer dependency grunt@~0.4.0 included from grunt-md2html will no
npm WARN peerDependencies longer be automatically installed to fulfill the peerDependency
npm WARN peerDependencies in npm 3+. Your application will need to depend on it explicitly.
```
seen on `npm install`.

Install grunt explicitly to stop warnings.

---

mithril.js

Nodes without a config function never get a configContext, and thus the
logic to ensure they are cleared on a full redraw was broken.

Fix nodes without config not being cleared when redraw strategy is all

---

.gitattributes

Let's not have PRs like this ever again: https://github.com/lhorie/mithril.js/compare/components...barneycarroll:3f3812917a035532c0cba268922bbf7dfc0e6d61

Avoid EOL diff horror by enforcing CRLF on commit

---

mithril.d.ts

Fixing a typescript compile error.

Fixing TS1016: A required parameter cannot follow an optional parameter

---

mithril.js
tests/mithril-tests.js

I understand the roadmap is to implement the ES6 promises, but in the meantime it'd be nice to have `.catch` on things like `m.request` :)
Example use case:
```javascript
m.request({ method: 'POST', url: '/profile' })
.catch(handleUnexpectedError)
```

Add `catch` to promise-like objects

---

docs/mithril.mount.md

Make clear that the user can optionally omit the controller.

Clarification on m.mount() signature

---

docs/components.md

Small typo, the docs were referencing a `broadcast` method from the preceding example, but it was supposed to be `trigger`.

components.md 'trigger', not 'broadcast'

---

mithril.js
tests/mithril-tests.js

This is the suggested diff from #632 for allowing component as the first argument to `m()` for interop with babel's `jsxPragma`.

accept component as first argument to m()

---

docs/routing.md

It's not completely obvious that `m.route.mode` needs setting before `m.route` is called (or at least it wasn't to me!), otherwise the initial routing from a URL typed in the location bar fails.  This PR adds a note in the documentation to make this more clear.

Clarify order of m.route.mode and m.route

---

docs/installation.md

Technically, Bower isn't really a package manager for Node.js, but rather, it's made in Node and built for usage in the frontend, hence why many popular frontend libraries, such as JQuery or Bootstrap have their distributions on there. Bower also has its own package repositories.

(docs) fixed bower description

---

mithril.js

We use the variable `FUNCTION` three lines earlier, so might as well stay consistent.

Consistency: use variable instead of literal

---

docs/mithril.component.md

It's a common question on Gitter: How do I unmount a component?
Presently, this Google search: `unmount site:http://lhorie.github.io/`
returns one result: `mithril.route.html` -- I have no idea why, there's no "unmount" on the page.
Adding the words **unmounting** and **unmount** to this doc page will make them discoverable directly and through Google.

Help users find documentation on unmounting components

---

mithril.js
tests/mithril-tests.js

Background:
In ES6 we now have `Object.setPrototypeOf` which makes prototype delegation an alternative to *sugary*, fake class coding patterns. This can be accomplished in ES5, but ES6 makes it much more elegant. Here is a basic example. `new` is never used and `this` is very easy to follow.
Working example with changes to mithril.js on lines 854, 858, 859 *only*.
http://jsbin.com/nopugo/1/edit?js,console,output
```javascript
'use strict'
const m = require('mithril')
const DataModel = {
data: [1,2,3],
getData(){
console.log('getting data from server')
return this.data
},
postData(val){
console.log('sending data to server')
this.data.push(val)
}
}
const ViewModel = {
filterEvenData: function() {
return this.getData().filter((val) => (val % 2 === 0) && (+val !== 0))
},
addNewData: …
```

allow m.withAttr callback to determine its own `this` [non-breaking]

---

mithril.js

Fixes #721: using Range.createContextualFragment (when available) instead of insertAdjacentHTML "beforend" which is buggy in Firefox.

Fixes #721. Firefox insertAdjacentHTML updating text nodes

---

mithril.js

Unfortunately, the fix for #727 did not fix the issue. The code need to also be placed inside the !isPrevented block. Also references in nodeCache cellCache needed to be cleared.

#745 Remove references to DOM nodes when unmounting (Follow-up to #727)

---

mithril.js
tests/mithril-tests.js

This behavior is inline with ES6.
Refs #680

Don't pass value/reason to promise.finally callback.

---

mithril.js
tests/mithril-tests.js

This is a pull-request for the feature suggested here: #737
I've tried adding a test to confirm the feature works. Did it through simple TDD. But I'd like to know if there's some special way tests are to be done (seems a bit confusing). I just copied another test focusing on params and query search string and modified it.

Make m.route.param() return all params

---

docs/routing.md

The link in current docs goes to 404. This PR suggests to fix the broken link and update the docs.
Never mind why line 112 diffed too.

Module -> mount rename: fix a documentation link

---

mithril.d.ts

Previously, the Typescript definition file did not support parameterized
components. The `component()` function did accept additional arguments, but the
`MithrilComponent<T>` interface did not allow components to have any additional
arguments in either their `controller()` or `view()` methods.
Properly supporting flexible variadic parameters in typescript is somewhat
challenging. Tuple types are close, but would only work if the signature of
`controller` and `view` accepted arrays of arguments:
```
interface MithrilStatic {
component<TController extend controller, TRest extends any[]>(
component: ParameterizedMithrilComponent<TController, TRest>,
...args:TRest
) : TController
}
interface ParameterizedMithrilComponent<TController extend controller, TRest
extends any[]> {
// Doesn't match …
```

Typescript: Support for Parameterized Components

---

mithril.d.ts

Two proposed commits, which would make MithrilVirtualElement and MithrilRoutes non-generic.
These changes are suggested because of issues arising from TypeScript's limited ability to infer types.  [This simple example](http://bit.ly/1JDvezX) on the Typescript playground illustrates the particular problem.
To illustrate in terms of Mithril, here is an example of a typical call to `m.route()`:
```TypeScript
m.route(document.body, "/a", {
"/a": ComponentA,
"/b": ComponentB,
})
```
In this example, assume both `ComponentA` and `ComponentB` implement `MithrilComponent<T extends
MithrilController>`, with each component having a different concrete controller
type (`ControllerA` and `ControllerB` respectively).
Unless ControllerA's type is a subset of ControllerB's type (or
vice-versa), …

Typescript: Make MithrilVirtualElement and MithrilRoutes non-generic

---

.eslintrc

It was supposed to permit `x|0` as well as `x | 0`.

Misread ESLint docs...(meant to allow `x|0`)

---

package.json

As per https://docs.npmjs.com/files/package.json#license, the package.json was using the old format, which throws a command line error when running `npm install`.
Shaves a few bytes off the repo too! ;)

Fix MIT license annotation in package.json

---

Gruntfile.js
package.json

My original intention was simply to avoid duplicating the version number more than necessary (it remains duplicated as a constant in mithril.js), but then figured we might as well treat the package.json as the config object that it is.
Note that the banner in the generated mithril.min.js changes to this:
/*
Mithril v0.2.1
http://mithril.js.org
(c) 2014-2015 Leo Horie
License: MIT
*/
...from this:
/*
Mithril v0.2.1
http://github.com/lhorie/mithril.js
(c) Leo Horie
License: MIT
*/
If you prefer to point towards the GitHub repo, then that line needs to be changed back to its former static value (`pkg.repository.url` is required to be the machine-readable clone url, so that can't really be used).

Read version number + other info from package.json

---

docs/installation.md
docs/layout/api.html
docs/layout/guide.html
docs/layout/index.html

Being pointed directly to a .zip-download from a link in the main navigation is a little jarring and unexpected for most users, I would wager.
And the user might as well be looking for one of the alternative options detailed on the [installation page](http://mithril.js.org/installation.html) — or if not, then the first link on that page is still to the .zip-file.

Point Download button and topnav link to installation.html

---

docs/installation.md

The text now reads "download a zip of the latest version here" instead of "[..] the latest version version here".

Fixes wording.

---

mithril.js

fixes #866, and should fix #614 as well
adds a handler to the unloaders array every time a controller is created.
Said handler removes the view from the views array and controller from the controllers array making sure that unload actually means "I should not exist anymore"

fix subcomponent unloading

---

mithril.js

In my hastiness to make #877 I forgot to use `Function.call` to call the unloading function.

fix hasty error

---

package.json

@lhorie 
Presumably, you're already using `npm version` to generate the tags before publishing, and this hooks into that, running `grunt build` before the version tag is generated. If you'd prefer some other hook, it's easy to change (and it's simple enough you could probably clone and push directly about as quickly).

Add preversion hook (fixes #827)

---

test/mithril.mount.js

fix https://github.com/lhorie/mithril.js/issues/826
- the previous test only remove last item on array, but expect all
subcomponent's onunload to be called. This PR change it by clear that
array.
- uncomment previous test case that marked fail.

Fix onunload test case

---

mithril.d.ts

The routes type doesn't need to be parametrized. It's far too restricting and technically incorrect.

Degenerify `MithrilRoutes`

---

README.md
docs/comparison.md
docs/getting-started.md
docs/layout/index.html

A very little nit-picky documentation change, but why not make mithril a tiny bit more beautiful!
I noticed the reference to a gzipped size of "7kb" throughout the docs.  "kb" refers to [kilobit, not kilobyte](https://en.wikipedia.org/wiki/Byte#Unit_symbol) and there should be [a space in between the number and unit symbol](https://en.wikipedia.org/wiki/International_System_of_Units#Unit_names_as_adjectives).

Small documentation tweak: kb -> kB

---

mithril.d.ts

I think this is a more accurate definition. I'm seeing errors when I use code like this:
```m("a", {href: "...}, "link")```
The error is:
```Argument of type 'string' is not assignable to parameter of type 'ParameterizedMithrilComponent<{}, { style: string; }, MithrilComponent<Controller>, void, void>'.
Property 'controller' is missing in type 'String'.```

update typescript defs to support more accurate MithrilAttributes interface

---

docs/mithril.component.md

This is a reapplication of #940 against `next` (I instinctively did `master` by accident).

Reapply docs fix

---

mithril.d.ts

m.withAttr() needed an additional overload/signature.
Added parameters to component controller and view functions.
These small tweaks silence almost all TS compiler errors for my app.

Typescript definitions updated for component and withAttr

---

docs/mithril.redraw.md

It seems this condition is put here to reassure users that redrawing in a given route state will not draw the views of components for other routes, but it's difficult to imagine how somebody might worry that might happen.
As it is, people end up believing that redraw acts per-component, which is highly misleading in a situation where there are nested components or multiple mount points, and the call to redraw is invoked within one of those components.

"Currently active component" is unhelpful at best, misleading at worst

---

mithril.d.ts

`MithrilPromise` returns the value it holds and not another promise that
holds the value. `MithrilPromiseProperty` was adjusted to act as a nested
`MithrilPromise`.

Fix definition of MithrilPromise

---

mithril.d.ts

Generic MithrilVirtualElement not have logic, because all parameters strong descripted in MithrilStatic function.
Rename module to namespace. Module is deprecated.
In projects need just rename strings in project with enabled regex:
MithrilVirtualElement<.+?> => MithrilVirtualElement

Remove generic from MithrilVirtualElement. Because him unused.

---

mithril.js
test/mithril.js
tests/mithril-tests.js

An empty attribute in the selector string is equivalent to an attribute with an empty string, as per [HTML spec](https://www.w3.org/TR/html-markup/syntax.html#syntax-attr-empty). [Here's a test case showing how the browser parses static HTML with an empty attribute](https://jsfiddle.net/barney/q70xx9du/).

Empty attributes. Fixes #971

---

mithril.d.ts

This is a more iterative redo of #992.
@lhorie Note that this won't be ready to merge for a bit. Also, note that I'm going to help ease migration for others by *not* flattening the Git history before it's merged, so they can look through that to run into fewer surprises.
/cc @LabEG

Remove redundant generics, improve accuracy and completeness of types

---

mithril.js

```
// code-that-calls-m.js
console.log('abc', m('a'));
```
With v0.2.3, running the following:
`traceur --script mithril-v0.2.3.js code-that-calls-m.js`
Results in:
`ModuleEvaluationError: m is not defined`
Expected result should be:
`abc { tag: 'a', attrs: {}, children: [] }`

Traceur Support

---

docs/getting-started.md

As brought up in #1019, mounting to the `document` can be problematic. Better to show mounting to `document.body` where things are a bit more straightforward.

[docs] mount to document.body instead

---

docs/getting-started.md

A minor continuation of #1023. This makes the code on the Summary section a working single-file application.
Without the `<body>` tag the code failed with "Error: Please ensure the DOM element exists before rendering a template into it" because the `<script>` containing the application was inserted and run on the `<head>`, before `document.body` is created.

Add <body> tag to Getting Started guide

---

mithril.js

Ref: https://github.com/lhorie/mithril.js/issues/199#issuecomment-210110023
Using latest of mithril and reactjs (15.0.1).
Table Rows | Mithril | ReactJs
:--------------- | :------------- | :-----------
100 | 37-41 | 38-44
500 | 162-165 | 147-166
1000 | 335-355 | 285-305
Table Rows | Mithril | ReactJs
:--------------- | :------------- | :-----------
100 | 27-35 | 57-62
500 | 85-91 | 176-185
1000 | 125-175 | 295-315
Table Rows | Mithril | ReactJs
:--------------- | :------------- | :-----------
100 | 21 - 31 | 38-44
500 | 65 - 75 | 147-166
1000 | 125 - 135 | 285-305
Table Rows | Mithril | ReactJs
:--------------- | :------------- | :-----------
100 | 27-35 | 57-62
500 | 85-91 | 176-185
1000 | 125-175 | 295-315
Perf test findings: https://github.com/spicyj/innerhtml-vs-createelement-vs-clonen …

Update: Big Perf improvement for IE (fixes #199)

---

examples/todomvc/todomvc.js

```todos.splice(index, 1)``` in destroy makes the elements shift; therefor loops index has to be aligned has to be corrected

correct index

---

mithril.js

Version 9.1 of Safari allows a maximum of 100 calls to pushState. Subsequent calls to pushState throw a SecurityError: DOM Exception 18: An attempt was made to break through the security policy of the user agent.
This jsfiddle shows the error in action when using Safari v9.1:
https://jsfiddle.net/j1sxxLwy/
In Safari Technology Preview v9.1.1, the implementation is improved to only cap pushState to 100 calls in a 30 second period. This jsfiddle shows that the error is not encountered when there is a delay between pushState calls in Safari Technology Preview v9.1.1, however it is still present in Safari v9.1:
https://jsfiddle.net/885yfab6/
So it seems that in future versions of Safari the pushState check will be improved to only prevent malicious or buggy code from executing. I've provided …

Force redirect when pushState encounters an error

---

mithril.js
test/mithril.trust.js

Details of problem are described on the issue page at https://github.com/lhorie/mithril.js/issues/1045
Adds a function `replaceScriptNodes` along with helper `buildExecutableNode` that check injected HTML for `<script>...</script>` nodes, and replace their contents with executable elements.
This function will only be called (AFAIK...) in Safari, since it throws on invocation of `createContextualFragment`, leading to the fallback onto `insertAdjacentHTML`.
Any feedback is welcome, including variable naming, whether the test should be in a different location, etc.
Thanks in advance! 👍

Correctly inject script tags via m.trust in Safari (Fix #1045)

---

package.json

Removing the noise seems pretty useful, and while it makes the CLI a bit ugly I prefer not littering the root of the repo w/ too many tiny config files.

Filter out util dirs from istanbul coverage reports

---

.eslintignore
.eslintrc.js
package.json

Manually changed some rules to better match @lhorie's style and reduce # of errors from ESLint.
Remaining errors:
```
/index.js
16:37  error  'Promise' is not defined  no-undef
/module/module.js
11:6  error  'base' is defined but never used    no-unused-vars
15:5  error  'module' is defined but never used  no-unused-vars
/querystring/build.js
19:13  error  'i' is already defined  no-redeclare
/querystring/parse.js
31:9  error  'key' is already defined  no-redeclare
/render/hyperscript.js
10:20  error  'id' is defined but never used  no-unused-vars
33:14  error  'key' is already defined        no-redeclare
/render/render.js
119:10  error  'o' is already defined       no-redeclare
130:9   error  'o' is already defined       no-redeclare
130:26  error  'v' is already defined …
```

[rewrite] Add ESLint and a generated config/ignore file

---

api/tests/test-mount.js
api/tests/test-router.js
api/tests/test-throttle.js
api/throttle.js

This is an implementation of my proposal to skip redraws via event handlers in #1044
Setting `e.redraw = false` in an event handler will prevent re-renders using either `m.route()` or `m.mount()`.

[rewrite] Skip redraw via property

---

.eslintrc.js

Because linebreaks are affected by git's `core.autocrlf` rule and I don't feel like adding a `.gitattributes` file yet.

Linebreaks are hard, spacing isn't

---

api/mount.js
api/redraw.js
api/router.js
api/tests/index.html
api/tests/test-mount.js
api/tests/test-redraw.js
api/tests/test-router.js
index.js

To better match `0.2.x` behavior: https://jsfiddle.net/xbpyqL9k/
Broke `m.redraw` out into a function and instead of having functions overwrite the `redraw.run` method they now push onto an array which gets run. I added short-circuit logic for the 0/1 cases that I'm not totally sold on, I should perf test that to see if it's worth the extra lines at all.

[rewrite] Add m.redraw() support for multiple mount points

---

docs/v1.x-migration.md

- `m("div", <component>)` is no longer valid
- `controller` no longer used in components

Add more migration notes

---

README.md

I believe js.org badge goes to the wrong location. So I changed it from *js.org* to *mithril.js.org/*.

Fixes js.org badge link.

---

package.json

See https://docs.npmjs.com/files/package.json#publishconfig and https://docs.npmjs.com/misc/config#tag
This way when `rewrite` starts being published to NPM users will need to install it as `npm install mithril@beta` to get the rewrite. When people run `npm install mithril` it'll continue to install the `0.2.x` branch until such time as things are ready to be cut over. Once that happens the whole `publishConfig` section can be removed.

Default to always using "beta" tag for rewrite

---

docs/integration.md

correct the code example to avoid infinite loop
the infinite loop occure because the code example also
update the value on change handler. issue #954.
prove https://jsfiddle.net/syaiful6/kps3gabo/

update integration docs

---

mithril.js
test/mithril.render.js
tests/mithril-tests.js

This implements https://github.com/lhorie/mithril.js/issues/1014 and incidentally fixes a broken test in the old test suite. I added tests to both suites since in gitter it was mentioned we can't delete the old suite yet.

Render booleans as empty strings

---

docs/v1.x-migration.md

Also made a change in the documentation around passing components to `m()`. Before, the syntax that was used made it look like jsx, which could easily have been misinterpreted. Since `component` is defined in the docs just prior, I don't think we need any special syntax to indicate that it might have been a placeholder value.

Add migration docs for m.route.prefix

---

mithril.js
test/mithril.render.js

This PR fixes #1091.
Basically, the \<select\>'s `value` weird behaviour was already considered on Mithril's code, but only for the case when the \<select\> node was initially created. I just moved that edge case code so it's also called when the node is being recycled, in case its \<option\>s change.
It seems to work fine, but i couldn't manage to do a regression test case to exercise this. The test case would need to use a real DOM, but also do a diff redraw. Something like this is enough for triggering the old buggy behaviour on browsers, and works well with this patch:
```javascript
var ctrl = m.mount(document.body, {
controller: function () {
this.value = "foo"
},
view: function (ctrl) {
return m("select", {value: ctrl.value}, [
m("option", {value: ctrl.value}, ctrl.value)
])
}
}) …
```

Fix #1091 Value on select tag not set when options are changed

---

index.d.ts
mithril.d.ts
package.json

Fixes #1107 
(I also had to fix the syntax.)
@lhorie BTW, TypeScript *does* find definition files under `node_modules` now, so it's best to upload it to npm now.
As a side effect, nobody needs to worry about keeping other versions (e.g. DefinitelyTyped) up to date.

Add definition file to npm

---

mithril.js
test/mithril.route.js

Hi! I stumbled upon this when trying to make a test for #1091 work.
Please take into account that i'm not familiarized at all with the Mithril codebase, so this proposed "fix" for the pending tests could totally be a nonsensical screwup!  :sweat_smile: 
---
When a controller calls preventDefault on its onunload method, it prevents the current root element from being unmounted via a route change. But it does not prevent it from being unmounted via m.mount(root, null). In that case, the root element is unmounted, but any unloaders that it had keep hanging on the `unloaders` array, and that prevented any future m.mount(root, component) calls from succeeding. This is what was happening on the pending route() tests.
The fix is pretty simple: just reset the `unloaders` array when removing the …

Remove unloaders when root element is removed

---

api/router.js

As first mentioned here: https://github.com/lhorie/mithril.js/issues/1044#issuecomment-223666077
Not changing underlying router APIs because those aren't really public anyways. If that's desired it would be simple to do, but doesn't seem worth it right now.

[rewrite] m.route.getPath/setPath -> m.route.get/set

---

mithril.js

Bugfix for issue #1124
The condition has been changed, which is deciding to push the a route to history stack.
I think, it is necessary to compare the old route with the current route, instead of old route with root (without parameters).

Push route to history stack, when using parameters #1124

---

docs/v1.x-migration.md
index.js
util/stream.js
util/tests/test-stream.js

This is written to behave like 0.2.x's `m.sync`. Also added migration docs.

Add m.prop.sync

---

api/autoredraw.js

This fixes the [fiddle](https://jsfiddle.net/nh12t8zy/1/), but #1149 still gives an error, probably due to the fact that the second mount occurs at redraw time and redraws are batched.
I'll add a proper test later (unless someone beats me to it).
(#1146)

Event handlers redraw all mount points. Fix #1146

---

.editorconfig

ESLint appears to define a tab as equivalent to four spaces, but the the lack of tab width specification in `.editorconfig` means that editors can still represent them however they wish.
This bug manifested for me because I've set tabs to be two spaces in my `.vimrc`, and I got unexpected line length errors when I ran `grunt lint`.

Specify tab width in editorconfig

---

mithril.js
test/mithril.trust.js

The regex in the current version of `getSubArrayCount()` miscounts nested elements in trusted content, leading to nodes that are inaccessible to the diffing algorithm. Additionally, text nodes lose the `$trusted` flag when cached in `reattachNodes()`, which causes `getSubArrayCount()` to default to returning 1.

Patch for #956: redraw trusted content with multiple nodes

---

api/tests/test-mount.js

Its failure breaks CI and having it break may be desirable.

Remove questionable test

---

render/render.js

Hello,
First, sorry for my poor english :-/
When updating the children of an `svg` element with its own namespace (e.g. adding new `rect`), its children have to be created by using `document.createElementNS` instead of `document.createElement` in order to specify their namespace.
Gaspar.

Pass namespace to new children when updating their parent

---

render/render.js

It makes it possible to access the `vnodes` tree from `oncreate` hooks (currently it is only possible from `onupdate` ones.

Move the `dom.vnodes` assignement up one line.

---

bundler/bundle.js
mithril.js

The current bundler script is renaming a lot of values unecessarily, and even [breaking some regexps that use the `m` flag](https://github.com/lhorie/mithril.js/commit/40b20538955fd3848060d9857499d37f69f1f376#commitcomment-18459435). This is because the generated RegExp for matching variables that are colliding is too loose currently. I've modified it by requiring a word-break before it matches the variable name, so variables like `m` don't cause havoc with any other variables that happen to end in `m` like `Stream` or `/gim`.
Original regex: https://www.debuggex.com/r/CikcfaudAYVAYC4U
PR regex: https://www.debuggex.com/r/-9FGfFlprnss2kaO
I've included the fixed bundle in this PR so you can verify the change. I ran both dbmonster & threadit w/o issue, I'm unaware of any bundler tests I …

Make bundle collision renaming more strict

---

api/throttle.js

`Date.now()` appears to be faster in every browser I have locally, was running benchmarks using [this bin](https://jsbin.com/tirelul/1/edit?js,console,output).
Browser | `Date.now()` | `new Date().getTime()`
------------ | ------------- | -------------
Chrome Stable | 7,739,075 ops/sec ±4.11% (56 runs sampled) | 4,618,586 ops/sec ±2.47% (62 runs sampled)
Edge | 11,053,165 ops/sec ±0.47% (64 runs sampled) | 6,705,249 ops/sec ±1.98% (58 runs sampled)
Firefox Dev Edition | 22,770,971 ops/sec ±2.41% (62 runs sampled) | 5,356,074 ops/sec ±1.39% (60 runs sampled)
IE 11 | 4,767,852 ops/sec ±0.71% (60 runs sampled) | 3,619,536 ops/sec ±1.13% (57 runs sampled)
I also compared some timings for the throttled function in dbmonster at 50% in chrome stable. I wrapped the main throttle function in …

Use Date.now() if available

---

docs/lifecycle-methods.md

The premature optimisation warning talks about `onbeforeupdate` as though returning false were its only purpose. In fact it's also useful for transforming simple input into a detailed model for the view, input-state comparisons for change highlighting, etc.

Gotchas imply onbeforeupdate is inherently evil

---

util/tests/test-stream.js

Here is a failing test of a problem I ran into today. The actual use case was trying to merge two `m.request`s together like so:
```js
m.request({ method: 'GET', url: 'http://example.com/user/10' })
.run(function (user) {
return m.request({ method: 'GET', url: `http://example.com/user/10/comments` })
.map( comments => Object.assign(user, { comments: comments }) )
})
.map(function (result) {
console.log("Result:", result)
})
```
I assumed this would behave like JavaScript's Promise absorption. Am I incorrect in my assumption? The problem (if it is a problem) is demonstrated by the failing test.

Add failing test case for stream

---

api/tests/test-mount.js

It's a bit involved, but I don't think it could be made much more simple...
As expected, it fails before [this commit](https://github.com/lhorie/mithril.js/commit/e0a0e97adae53a29d32c66e6394cb9504f68c0da#diff-b8715a148e2f2e37b1bf0d37ce95aae9) and succeeds afterwards.

Test for #1146 and #1153

---

.travis.yml
package.json

No reason everyone who wants to do local dev should need to install `travis-scripts`, only the build server ever cares about them.

Move travis-scripts to be build-server only

---

docs/v1.x-migration.md

@tivac: split from #1172 ss discussed in the gitter chat

Migration docs: m.mount and m.route now require components where vdom nodes were once tolerated

---

api/mount.js
api/tests/test-mount.js
docs/mount.md

This is a better version of #1169.
Passing `null` unmounts the component and removes the renderer from the `pubsub` array. 
Replacing a mounted component removes the previous renderer.
I've also added a note about mounting vnodes not working in `v1.x`.

Unmount and cleanly refresh mount points

---

render/render.js

I can't for the life of me reduce this to a simple example, but here is the code in question from one of my projects: http://jsbin.com/kupoyubeta/1/edit?js,output . Unfortunately it works there, but this is what I'm seeing in my project:
1. Click a button, div animates in.
2. Later, a redraw occurs, and I get this error:
Uncaught TypeError: Cannot set property style of #<HTMLElement> which has only a getter
Upon further investigation, I discovered the `element.style = ""` line was, for some reason, the culprit. Changing it to use cssText fixed it, and is apparently the official way to do it. https://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-CSSStyleDeclaration-cssText

Set element style using cssText

---

api/mount.js
render/render.js
render/tests/index.html
render/tests/test-render.js

https://gitter.im/lhorie/mithril.js?at=57a4e8c7978997001e99ae35
> **tivac** Huh
> **tivac** when you `m.mount` into an element w/ the rewrite it doesn't overwrite existing content
> **tivac** `rewrite` - https://jsbin.com/titama/edit?html,js,output
> **tivac** `0.2.5` - https://jsbin.com/kopakex/1/edit?html,js,output
https://gitter.im/lhorie/mithril.js?at=57a4ea65d097eb6b2cc89f6c
> **tivac** @mindeavor @lhorie [docs for `m.mount`](https://github.com/lhorie/mithril.js/blob/rewrite/docs/mount.md) don't seem to clearly state one way or another if it should blow up existing non-mithril DOM elements.
> **tivac** So I wonder if this is intended behavior or not
> **tivac** TO THE TESTS
> **tivac** No tests for or against this behavior
https://gitter.im/lhorie/mithril.js?at=57a4ebc9fb162b752ca18d5 …

render clears non-mithril dom nodes

---

render/render.js
render/tests/test-updateNodes.js

... and obsoletes #1220.
I use explicit tests, but using one loose equality test (`if (old == vnodes){}`, likewise for individual nodes) may also work and would do the same behind the scenes. I'm not equipped for benchmarking Mithril right now, though, so I'll leave it to you.

Skip diff for cached, non-keyed nodes fix #1206

---

render/render.js

According to the [WhatWG DOM spec](https://dom.spec.whatwg.org/#dom-document-createelement), `createElement` and `createElementNS` dont take `is`, but an `option` object as a last, optional parameter. Its `is` property is used for the custom element lookup.
Caveat: I did not test this in any way nor do I have any experience with custom elements. I just noticed the discrepancy.

`is` should be passed as `{is: is}`

---

test-utils/domMock.js

A leftover of the original `j2c` implementation that splits selectors. Sorry for the noise.

Remove an unused variable

---

mithril.js
test/mithril.prop.js

When JSON serializing `m.prop`, check if wrapped object does define `toJSON` method
and if so, return it's result.
I'm not sure how to properly test javascript code, so please check everything before.

JSON.stringify(m.prop(x)) use x.toJSON method when possible

---

mithril.js

Ran into an issue with isomorphism - if I change a model on the server, it may in some circumstances try to re-render, and throw an error:
TypeError: $requestAnimationFrame is not a function
To circumvent this, we check for the availability of 'window', and set mocked dependencies instead.

Set dependencies when no window for isomorphic compatibility

---

index.js

The current bundles were throwing "Stream is not a function".
The proper place to fix this would probably be in the bundler, but for now this circumvents the issue.
It appears the instantiated "Stream" will be cached and used inside the requestService that also requires './util/stream',  instead of just what's inside './util/stream'.

Temporary fix for broken bundles

---

index.js
mithril.js
stream/index.js

@lhorie 
Here is the pr for https://github.com/lhorie/mithril.js/issues/1239
I moved streams into their own folder and created an index.js file there so that streams can be required in this way:
```js
import stream from 'mithril/stream';
```
If you prefer a root-level stream.js file, I can change that.
The bundler seemed to have trouble recognizing the index.js import, so I had to manually require `./stream/index`, so maybe a future pr can make that work more like commonjs.
I do not believe this can be merged as-is. Not sure what happened, but in the build the streams ended up being numbered `stream1` `stream2` etc.
Anyway, this can be used as a starting point. Any guidance for how to make this cooperate with the rest of the build setup would be appreciated.
**Edit:** Just realized the …

Piecemeal stream usage

---

render/render.js
render/vnode.js

I remember reading that `vnode` fields not defined statically were oversights, so here we are :-)

Add a static `vnode.skip` field

---

docs/route.md

Table formatting was broken, and the code example had `use` instead of `resolve`.
Wasn't sure about the `required` column, so it's blank for now.

Update route.md docs

---

api/mount.js

No need to create a dummy vnode.

Better cleanup when unmounting

---

mithril.js

See #1252
#348 was also re-broken in two separate events. The second `!=` was likely transformed by the linter (but the comment was preserved :-), and I didn't dig for the (earlier) regression on the first one.
As of `v0.1.25`, [both tests were loose](https://github.com/dhinesh03/mithril.js/blob/v0.1.25/mithril.js#L347-L357).

Fix #1252, re-fix #348

---

render/render.js
render/tests/test-onbeforeremove.js
render/tests/test-onremove.js

This is best viewed with `?w=1` to ignore indentation changes.
Without this, it is possible to run each `onremove` hook twice if a component has the `done()` callback called synchronously from the `attrs.onbeforeremove` hook.
There may be better ways to implement this, I did what seemed the simplest to me.

Robust onbeforeremove

---

hyperscript.js
index.js
render/fragment.js
render/tests/test-fragment.js

As announced in #1241, I've also added `./hyperscript`, which combines `render/hyperscript`, `render.raw` and `render.fragment`.

Add `m.fragment()`

---

docs/route.md

..unless the code sample is wrong, in which case `render:` should be replaced with `view:`

fix typo in RouteResolver description

---

ospec/ospec.js
ospec/tests/test-ospec.js

Currently tests need to take a very different approach as soon as you need to ensure that a function was called but also have that function fulfil its own arbitrary functionality.
This re-introduces the valuable ability to allow spying on functions whose side effects and return values the tests may depend on.

[ospec] allow spy to wrap functions

---

api/router.js
api/tests/test-router.js
docs/route.md
index.js
route.js
router/router.js
router/tests/test-defineRoutes.js
tests/test-api.js

There :-)
This builds  on top of #1290 and finalizes my effort to improve the router by fixing #1269.
This makes `m.route(...)` synchronous like `m.mount` unless there's no match (in that case `router.setPath()` is called, and it can't be made synchronous due to `onhashchange` semantics).
Note that the `replay` function (which is now synchronous too) is not available anymore.
~~Oooohh... we could make redirection synchronous by temporarily disabling `onhashchange`/`onpopstate` and calling `replay()` while the handlers are inactive...~~ Edit: no, that would break "nested" routing.
BTW, the tests are now 500 ms faster than they were before I added the five extra `api/router` ones.

Router: Add debounceAsync to normalize the timing of onhashchange and onpopstate.

---

api/router.js

The `resolve` function can be used as a unique `resolveIdentifier`.
This saves a glorious total of four bytes after minification and compression.

Simplify resolution identifier logic (just a bit)

---

mithril.js

I suppose the `mount` version is there due to possibly delayed `render` calls.

[next] Use identical error messages, improve gzipped size

---

CONTRIBUTING.md
mithril.js
test/mithril.render.js
test/mithril.trust.js

This is a rebased version of #900 with a proper commit message.
Also, the `m.trust()` test that was excluded is actually working!
#900 will probably have to be closed manually.

Rebase #900, reactivate m.trust test.

---

util/stream.js
util/tests/test-stream.js

Based on #1307 
Passing a non-stream value to combine or merge will result in uncaught
errors.  This is one way to resolve it without adding a lot more bloat.
I thought to pre-filter or loop through the streams when `combine` is called to validate them prior to calling `initDependency`, but that seems like it may be unnecessary overhead.  Happy to make adjustments based on feedback.
EDIT: This doesn't actually stop the loop - I think that may be due mount attempting to re-render?  I'm not sure if it would make sense to allow the dependency to initialize but keep it in an errored state instead, then? (i.e. validate the streams and only pass valid items to `initDependency`, then throw manually in the callback)

WIP - Prevent Infinite Loop in m.prop.combine

---

querystring/parse.js
querystring/tests/test-parseQueryString.js

Route to:
```
/login?message=Please%20log%20in%20to%20view%20this%20page&previous=%2Fen%2Fedit%2F1
```
The route contains a form that will set the path to the `previous` attr on successful login.  (Maybe this is a weird pattern but it seemed like a good idea at the time).
```
TypeError: path.indexOf is not a function(…)
```
Native Date parsing is unpredictable and will occasionally turn a string
like "/foo/1" into a valid date of Jan 1, 2001.  This can be prevented
by not parsing a string that begins with a slash.
It's likely that this is a rare case, but it's annoying when it does
come up.
I wonder if there might be another issue hidden in here though - I'm not really sure why the path wouldn't be a string and therefore throw that type error.

[rewrite] queryString parse - Prevent undesired date parsing

---

docs/hyperscript.md

Moved SVG/MathML section down to reflect the order of the TOC
Renamed "Avoid Anti-patterns" to enable TOC link

small fixes in hyperscript.md

---

render/hyperscript.js

This is already covered [here](https://github.com/lhorie/mithril.js/blob/9fbcea2d067ef3f28877c626c10f33a2643345fd/hyperscript.js).
Non-bundle examples are broken by the lines removed here (since they don't load `render/trust.js` and `render/fragment.js`). I could have fixed them, but this is easier :-)

[rewrite] Remove redundant lines that break the examples

---

api/router.js
api/tests/test-router.js

Currently, changing the `key` on the `vnode` of a routed component doesn't have any effect. This prevents the re-initialization of components in user-defined circumstances.

[rewrite] respect keys on routed components.

---

ospec/README.md
ospec/package.json

Getting set up with ospec is deceptively simple, and adding just a bit
more documentation should help new users from falling into the trap of
overthinking the test config.  I know that I ended up down a very
strange rabbit hole when pulling ospec into a small project -- 
trying to use rollup and all kinds of goofy things on my test files. 😅
This also adjusts the bin definition in the package file so that we can
hopefully just use the `ospec` command instead of a folder ref.
---
I know that the current bin definition *should* work, but the `ospec` command doesn't seem to work for me when installing to other projects so I'm trying to see if explicitly declaring the name will help to fix that.

[rewrite:ospec] Adjust ospec bin def, add to README

---

router/router.js

Currently, middle clicking and ctrl+click change the route in the current tab. Expected behavior is to open a new tab/window. This line was pulled verbatim from v0.2.5. Was the absence of this feature of an oversight?

[rewrite] Ignore modifier+click and middle click in m.route.link

---

docs/v1.x-migration.md

I am not sure you agree, but i find the name `state` a bit less confusing that the name `ctrl` used in v.0.2.x. At 1st sight i asked myself "what controller?", right after I read there was no `controller` function anymore.
thank you and kind regards

upgrade doc: rename ctrl to state

---

render/vnode.js

Hello @lhorie,
maybe this can be thought more as a style habit. I always rewrite conditions that only return values like this:
```js
// pseudo-code
function getSomething() {
if (cond1) {
// do something
return value1;
} else if (cond2) {
// do something
return value2;
} else if (cond3) {
// do something
return value3;
} else {
return default;
}
}
``` 
to
```js
// pseudo-code
function getSomething() {
if (cond1) {
// do something
return value1;
} 
if (cond2) {
// do something
return value2;
}
if (cond3) {
// do something
return value3;
}
return default;
}
``` 
and of course with 1 line condition/expression pairs they look like shorter version of switch() with the benefit of the availability of strict type checking in conditions.
```js
// pseudo-code
function getSomething() {
if (cond1) …
```

remove unneeded else

---

index.d.ts
mithril.d.ts

This fixes both TypeScript inconsistencies.

Fixed #1343, #1336.

---

mithril.js

By using 'catch' word that is reserved word in JavaScript, Syntax Error is occured in IE 8 / 9 with parsing mithril code.
To fix it, enclose 'catch' word with [].
Thanks.

'catch' is a reserved word in IE 8 / 9

---

render/render.js
render/tests/test-updateElement.js

When updating an SVG element and changing its tag, the namespace is lost and the element becomes unknown HTML. See new test case.
Thanks for mithril!
Thibault @ lichess.org

Add failing test and proposed fix for SVG update with tag change.

---

README.md
bundler/cli.js
bundler/minify.js

Break the minify stats output into a callback in `cli.js` since it really only makes sense in the CLI context anyways. Also lets me do the readme rewriting w/o it feeling weird living in `minify.js`.
Added some HTML comments around the size so it's easy to target via a dumb regex & updated every time `build-min` is run.

[rewrite] Update README size w/ minified builds

---

docs/request.md

I thought the behaviour of extract could use this extra note.

Add note about JSON parsing behaviour with extract callback

---

docs/components.md

These additions would likely need fixing, but I think it would be helpful to add a couple of things:
1. Explain how to send data to a component. I think people will want to understand this early in a discussion of Components. `attrs` appears later in this document without much explanation.
2. A warning about using lifecycle method names accidentally as your own callback function names.
I'm still a bit hazy myself on the seemingly interchangable use of the words vnode and attrs.

Passing data to components, avoid inadvertant lifecycle hooks

---

stream/stream.js

Use Array.prototype.some and Array.prototype.every to make code a bit easier to read (plus we get to shave off a few bytes on the way...)

[rewrite] simplify array operators in stream

---

render/render.js

This fixes #1413 for a case that was not covered by #1415 , when setting `value` property of `select` tag directly as in here:
```js
m('select', { value: myvalue },  options.map(renderOption))
```

Fix blinking select in chrome when setting select property in select tag

---

package.json

This allows you to `npm run build` after `npm i` without having to globally install Grunt CLI.

Remove Grunt path dependency by aliasing core Grunt tasks to NPM

---

docs/components.md
docs/hyperscript.md

An attempt at documenting the gotcha that subsequent renders will skip referentially equal vnodes, potentially leading to sections of the tree falling out of sync, lifecycle methods not triggering as expected, etc.
Here's a couple of jsbins illustrating the [AVOID](https://jsbin.com/nomupa/edit?js,output) and [PREFER](https://jsbin.com/kowepek/edit?js,output) examples from the component anti-patterns section.

Document equality diff skip - fixes #1429

---

docs/components.md

@cmawhorter [pointed out on the chat](https://gitter.im/lhorie/mithril.js?at=583a4b0e89d179bf4dcc2f1c) that the component's anti-pattern documentation section '[avoid restrictive interfaces](https://github.com/lhorie/mithril.js/blob/b87cf7b28853aab4cd306afc24d7507b81027c32/docs/components.md#avoid-restrictive-interfaces)' seems to be immediately contradicted by 'avoid magic indices'.
I think the overall tone of the anti patterns section comes across as distant and dogmatic, the wording is too imperative and technical without acknowledging circumstantial nuance.
This redraft attempts to make it clearer that these two sections are intended to be read together as examples of when custom interfaces are and aren't desirable. 
Ultimately I think this subject should be taken out of 'avoid …

Demystify component antipatterns

---

docs/v1.x-migration.md

Complements #1433 in a bid to close #1429

Document array semantics and vnode equality logic in migration guide

---

.travis.yml
index.js

This will slow down builds a bit, but only the CI ones. Locally running `npm test ` will still just run the tests.
This will solve issues like what @pygy is running into on #1339

Travis should lint & bundle on every build

---

docs/v1.x-migration.md

http://mithril.js.org/mithril.redraw.html#forcing-redraw appears to be gone, based on both docs and a quick perusal of the code. This should be documented in the migration guide.

Document removal of sync redraw

---

README.md

Wasn't sure whether there's a desire to update the text as well, but just noticed the links are busted so thought a PR might help :-)

Fix broken migration links in readme

---

render/render.js

This makes event binding less wasteful, more efficient, and faster in cases when there is no `renderer.setEventCallback` registered.

Improve event binding

---

docs/route.md

- Fix "Changing router prefix" TOC link
- Remove old `m.request.run` ref
- Use shorthand `m.request` notation

Minor m.route docs cleanup

---

api/router.js
router/router.js

:warning: **This is still a WIP and needs some eyeballs/opinions!** :warning:
This came up [in Gitter](https://gitter.im/lhorie/mithril.js?at=5845bfb6b4ffd59e38ec53f1) while chatting about what to do with `onmatch` and `resolve` because it's really easy to footgun yourself with the current API. Props to @barneycarroll for the idea, I just had some time to hack it out.
1. All `onmatch` functions are wrapped in a `Promise.resolve()` so they can consume whatever return value they're given and they are always async. That seems like a reasonable standardization to me, especially in light of `m.route.set()` already being normalized to be always-async as well.
2. `m.route.set()` returns a Promise. This is intended both to work nicely with the `onmatch` changes as well as be a bit more …

[WIP] Use promises in router

---

promise/tests/test-promise.js
request/tests/test-request.js

These tests validate the scenario in #1465. The tests work for Mithril's promise implementation but don't for `m.request`.

Test branched rejection handler resolution

---

api/tests/test-router.js
test-utils/browserMock.js
test-utils/pushStateMock.js
test-utils/tests/index.html
test-utils/tests/test-browserMock.js

I was adding tests and noticed that the mocks were inadequate to write them... Pushing one commit at a time for CI confirmation.
The description will be fleshed out once the router tests are pushed.
----
Edit... I had to rebase it, so much for individual CI reports...
So for the mocks, it turns out that the `pushState` functions didn't have a reference to `$window` in the `browserMock` because of how the latter was being built. This is now fixed. I found other mock bugs, but the fix require more extensive investigation, I'll open other issues.
When redirecting from `onmatch` if you replace 
`m.route.set('/foo')` 
with 
`callAsync(_ => m.route.set('/foo'))`
or
`$window.history.back()`,
`update` fires unless you return a pending promise. I've added inline `return new Promise(function(){})` …

[rewrite] (WIP) A few more tests for the router + mock fixes

---

.npmignore

Currently the package being published to NPM has a bunch of cruft in it. Adding a `.npmignore` file to hopefully clear out most of it.
You can see how much it cleans up the directory after installation by comparing this diff: https://www.diffchecker.com/N11MonGi
And I've got half a mind to exclude the `docs` dir too, since I don't think most people read docs out of their `node_modules` directory.

Clean up npm package some

---

api/router.js
api/tests/test-router.js

... but it doesn't. The test also fails pre #1471, but differently (the second route is finalised too soon, because of the line I pointed to in one of the comments).
WIP, working on a fix.

[rewrite: router] Racing two onmatch w/ delayed resolution, the second one should win

---

.npmignore

This reverts most of #1449, with the opinion that while the files relating exclusively to development, contribution and deployment aren't relevant to the NPM package, a lot of the other stuff can be useful and should stay.
The pros on keeping the NPM package extra trim:
1. As @tivac says in #1449, getting rid of cruft
2. Smaller npm downloads
On the other hand:
1. Mithril is far from needing to compete aggressively on those features compared to any other given package. If a given user suffers from the clutter or weight of their npm installs, Mithril will almost certainly be at the bottom of the list of offenders - which makes the effort to prune back kind of pyrrhic. 
2. The clutter argument is irrelevant for people who configure their IDEs / text editors to ignore the contents of …

Keep useful utilities in the npm package

---

index.js
render/render.js

Mostly for use in `mithril-objectify`, but may be useful in other places.
Doing this so I can make a `rewrite`-compatible version of `mithril-objectify` that doesn't have to be aware of the bundling stuff going on. It can just replace invocations of `m(...)` with `m.render.vnode(...)` and go on it's merry way. Without this I would need to detect the type of bundling environment (CJS/ES2015) and then dynamically inject a `require`/`import` statement to get access to `Vnode`. I can do that, but I'd really rather not.
I wondered about exposing this as `m.vnode` or `m._vnode` but `m.render.vnode` seemed like the most appropriate place for it.

Expose `Vnode` as `m.vnode`

---

api/tests/test-router.js

This means the test fails without the fix in #1492 but passes with it :-)

Ensure the back button test checks the right thing.

---

ospec/bin/ospec

It shaves one second for `j2c`.

[ospec] Speed up the CLI runner by skipping node_modules early

---

docs/request.md
request/request.js
request/tests/test-request.js
test-utils/xhrMock.js

I also had to edit the mocks accordingly, so I could inspect the headers set.

Add support for `options.headers` in `m.request` + tests/docs

---

ospec/tests/test-ospec.js

As far as I can tell, this `o.only` is disabling the execution of all the tests in the Mithril test suite.
This pr reactivates them.
eg
```
1 assertions completed in 6ms, of which 0 failed
242 assertions completed in 16ms, of which 0 failed
```
vs
```
1 assertions completed in 6ms, of which 0 failed
5682 assertions completed in 1529ms, of which 0 failed
```

Remove o.only call to ensure other tests are run.

---

docs/route.md

It's confusingly similar to previous block, and now aligns with actual written text below.

Remove extra code from example that is not required

---

render/render.js

Since our baseline target runtime is IE9-safe ES5, we can avoid convoluted temporary constructors and use `Object.create` instead.

Avoid intermediary component constructor

---

render/tests/test-component.js
render/tests/test-hyperscript.js
render/tests/test-normalize.js
render/tests/test-normalizeChildren.js
render/vnode.js

Fixes #1014
Adds a `=== false` check within `vnode.normalize` that will output an empty text node instead of one that says "false". Also updated tests for new behavior (there's a surprising number of tests checking for behavior of passing `false` as a child!).
This simplifies a lot of view code that does conditional logic.
```js
m("div", test ? [ ... ] : null)
// can now be this, assuming test is strictly false
m("div", test && [ ... ])
```
It doesn't seem like a big change but in practice it can be hugely beneficial for making deeply-nested view code easier to read.
**Note:** this does **not** match the `0.2x` behavior introduced in #1103 where `true` values are also ignored. That behavior is more consistent but seems a bit off the more I think about it. If that's the preferred behavior …

Render false as an empty string

---

ospec/ospec.js

It will run all tests, even if more than two share the same name. This covers the case were the attempted deduped name already exists.
AFAIK mutating a function argument can cause deopts in V8. Removing these mutations doesn't seem to affect the run time but better be safe than sorry...
At last `[\w_]` is redundant since `\w` matches `_`.

[ospec] Improve the dupe detection code

---

mithril.closure-compiler-externs.js

Add @externs annotation. This is required by the Closure compiler, at least when used through rules_closure: https://github.com/bazelbuild/rules_closure#closure_js_library. It is a common practice, too, eg.
https://github.com/google/closure-compiler/blob/master/externs/es5.js
https://github.com/steida/react-externs/blob/master/externs.js

Add @externs annotation.

---

api/router.js
api/tests/test-router.js

There are plenty of use-cases for having components further down the tree able to investigate the route params, and currently the only way to make that available is to pass around the `vnode.attrs` and/or stash it away somewhere. Looking at `api/router.js` those params are already kept available to anyone, so this PR revives the `m.route.param(<key>)` method from `0.2.x` to simplify that same usage in `1.0.0`.
The impetus for this is trying to port an existing `0.2.x` app of ours that has deeply-nested child components that inspect the current route state for a portion of their functionality. We could do a large refactor to make the data available in a different way but I don't think there's much point. I don't find `m.route.param()` to be a particularly offensive API, I think I just …

Revive m.route.param()

---

ospec/bin/ospec

I've encountered the problem of `stat` is undefined, throw below error:
```
/home/1111hui/public_html/node_modules/ospec/bin/ospec:13
if (stat.isDirectory()) {
^
TypeError: Cannot read property 'isDirectory' of undefined
at /home/1111hui/public_html/node_modules/ospec/bin/ospec:13:12
at FSReqWrap.oncomplete (fs.js:123:15)
```
I've checked it's due to some unicode file names on some linux OS.
Maybe this fix is not perfect, but it works.

fix: stat is undefined in some cornor case

---

request/request.js

Aborting an XHR request after it has been sent but not finished results in an error. To reproduce the XHR state in a browser:
```
var xhr = new XMLHttpRequest();
xhr.onreadystatechange = function() {
console.log('readyState:', xhr.readyState, 'status:', xhr.status);
};
xhr.open('GET', '/', true);
xhr.send();
setTimeout(function(){ xhr.abort() }, 10);
```
Should make you see `readyState: 4 status: 0` in the console.
The current xhrMock in Mithril is not capable of reproducing the error.

Fix request abort error

---

.travis.yml
package.json

New release process:
1. Programmer enters `npm version <type-of-change or new version> -m "v%s"`
Everything else is fully automated, here's what will happen.
1. Tests are run
3. Linting is run (but doesn't fail build)
4. Version number in `package.json` is incremented
5. New bundles are generated using updated version
6. `git add` called on bundle output
7. `package.json` and updated bundles are committed to git
8. previous commit is tagged using new version number
9. `git push --follow-tags` pushes up new version commit & tag to github
10. Travis sees new release, starts build
11. Travis generates new bundles before running tests
12. Travis runs tests
13. Travis lints files (but can't fail build)
13. If build fails, abort
14. Build succeeded, so travis will commit back any changes to the …

Use Travis for npm publishing

---

.travis.yml
docs/releasing.md

Don't love pushing straight to your repo, so doing this via PR.
This is an attempt to make `.travis.yml` easier to read and also pull the docs from #1538 and making them slightly more permanent. I don't want to presume on the process for setting up the GitHub Release or editing `change-log.md` so left those as a `TODO`.

docs: Document release process & reformat .travis.yml

---

docs/lifecycle-methods.md

Fixed the description of onremove to match the current implementation of onbeforeremove (promise vs. done callback)

fixed onremove lifecycle doc

---

docs/autoredraw.md

Add explicit note that Mithril does not autoredraw on `Promise` resolution, even when you use Mithril's `Promise`.
#1546 followup.

Docs: mithril does not autoredraw on `Promise` resolutions. #1546

---

docs/style.css

| Before | After |
| --- | --- |
| ![before_iphone6](https://cloud.githubusercontent.com/assets/83627/22462316/b2ec056e-e7a4-11e6-97e3-1bd3b9b0a212.jpg) | ![after_iphone6](https://cloud.githubusercontent.com/assets/83627/22462318/b4f74d46-e7a4-11e6-9357-9eaba2bb4dff.jpg) |

Fix docs text size variations on mobile webkit

---

docs/index.md

Declaring scripts after the closing body tag looks like a typo

Docs: intro: valid HTML snippet

---

README.md

The use of the word "Performance" can be confusing in the speed comparison chart, because a shorter line means faster rendering and so higher performance -- compared to interpreting that performance line as operations per unit time at a first glance. "Rendering Time" as suggested on gitter by @brlewis makes clear that a shorter line is better.

Update README.md to clarify speed comparison chart

---

LICENSE

I'm guessing the license file was missed in the move to 1.0.0. I bumped the year of the copyright, but otherwise according to the [website](http://mithril.js.org) the license is still MIT.

Adding license file.

---

docs/change-log.md

This change apparently went completely unnoticed by me until now.
Already supported in `mithril-codemods@3.5.0` though!

docs: add m.route.build/parseQueryString to changelog

---

render/render.js
render/tests/test-oninit.js

**This was done for 0.2.5 but forgotten for 1.0.0** : https://github.com/lhorie/mithril.js/issues/1090#issuecomment-276273990
Here is the previous PR: #1016
Issue comment: https://github.com/lhorie/mithril.js/issues/199#issuecomment-210110023
This should give enough information.
**Theme:** Add the element to its parent before you add its children to it. this has perf improvements on IE engines (including Edge).

Update: Add elem to parent before adding its children

---

ospec/ospec.js
ospec/tests/test-ospec.js

This outputs a red `/!\ WARNING /!\ o.only() mode` banner to `stdout` when `o.only()` is used.

[ospec] Make some moise when `o.only()` is called

---

docs/testing.md

It's not immediately obvious how to use mithril in a non-browser environment, so adding some docs to clarify how to accomplish it.

docs: setting up mocks in non-browser env

---

mithril.d.ts
package.json

This PR adds Typescript definitions for 1.0. It adds the file `mithril.d.ts` and adds the entry `"types": "mithril.d.ts"` to `package.json` (analagous to `"main": "mithril.js"`.)
Thought I'd submit this so you can take a look at it and decide whether or not to include types with mithril or if I should add them to DefintelyTyped. Just a couple of points to make:
1. On NPM typescript is now getting about half the installs of babel-core. A lot of people use it.
2. For people who write JS, VSCode (and perhaps other editors, I'm not sure) can take advantage of TS types for JS type hinting.
If you want to test this fork on a typescript project, you can `npm install -S github:spacejack/mithril.js#typescript-types`

Typescript Definitions for 1.0

---

ospec/ospec.js
ospec/tests/test-ospec.js

This makes nested test definitions and assertions out of test blocks throw an error.
#1339 for the rationale (even though #1617 makes this partly redundant).

[ospec] stricter valid context for test definitions and assertions

---

docs/fragment.md
docs/jsonp.md
docs/route.md

Fixes should be self-explanatory I think. I've been testing a lot of API signatures while I finish up some loose ends with the typescript definitions.
I made an incomplete change to RouteResolver's `render` signature, though to be more correct it would be more like:
**returns** `Vnode|String|Number|Boolean|null|undefined|Array<Vnode|String|Number|Boolean|null|undefined>`
which gets kinda long for the table. Still it's useful to know more concretely what the types are.
I wonder if it would be useful to describe a "Renderable" type somewhere and reference that wherever needed.

API docs signature fixes for route resolver, jsonp, fragment

---

render/hyperscript.js
render/render.js
render/tests/test-component.js
render/tests/test-hyperscript.js
render/tests/test-render.js

A cleaned up version of #1338, minimally invasive.
It is still a bit bare bones (we could for example add a `view()` methods to `m.Component`'s prototype, the tests could be fleshed out) and there are no docs.

Support classes and factories as components

---

.travis.yml

This is why #1339 (and maybe other PRs) didn't trigger a build.

Make Gandalf builds track next rather than rewrite

---

stream/package.json

Fixes #1629
Had to guess at a name, `stream` is already taken. Something cooler is probably preferable!

Make streams publishable to NPM

---

api/mount.js
api/router.js
api/tests/test-mount.js
api/tests/test-router.js

So, I forgot to relax the component tests in `m.mount()` and `m.route`. TODO:

Let `m.mount` and `m.route` accept class and factory components.

---

request/request.js
request/tests/test-request.js
test-utils/xhrMock.js

The xhr.status can equal zero in non-abort scenarios, eg timeout or CORS failure.
The current handling means that the request promise doesn't reject for a CORS failure or for a timeout.
Rather than inferring that xhr.status === 0 means abort, track the invocation of the abort function instead.
Mostly making this PR as a RFC... (And to check I didn't miss something logical :-) )

Avoid inaccurately inferring xhr abort.

---

render/render.js

This is a rough attempt at a fix for #1593, with zero consideration given to potential side-effects. Just something to get started discussing more than anything.

Loose comparison when early-outing from setting attributes

---

request/request.js

m.request's document says
```
Force the use of the HTTP body section for data in GET requests when set to true.
```
But body may have any contents with GET request and server should ignore it:
http://stackoverflow.com/questions/5725430/http-test-server-that-accepts-get-post-calls
And MDN says the body is completely ignored when the method is GET or HEAD.
And I tried on Chrome, the server doesn't receive any bodies even if ```useBody: true```.
https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/send
My extra concern:
* Should I add "HEAD" to the condition?

When method is GET and TRACE, useBody becomes always false

---

api/tests/index.html
api/tests/test-mount.js
api/tests/test-router.js
render/tests/index.html
render/tests/test-component.js
render/tests/test-onbeforeremove.js
render/tests/test-onbeforeupdate.js
render/tests/test-onremove.js
render/tests/test-render.js
render/tests/test-updateNodes.js
test-utils/components.js
test-utils/tests/index.html
test-utils/tests/test-components.js
tests/test-api.js

Edit: build failure due to flaky test timeout. 
Edit2: [review link with white space diff ignored](https://github.com/lhorie/mithril.js/pull/1643/files?w=1) Original follows.
This runs most component-related tests on POJO, closure and constructible components. I've left out the `api/router.js` tests because segregating test with and without components without losing the tests organisation was not obvious.
With each step but the last one and 90b67b4 the total number of assertions remains identical.
For posterity, here's the jscodeshift script used to wrap some of the components:
```JS
module.exports = (file, api) => {
var j = api.jscodeshift,
s = api.stats;
return j(file.source)
.find(j.VariableDeclarator, {
id : {name : "component"}
})
.forEach(() => {
s("component")
})
.replaceWith((p) …
```

Test all component kinds

---

docs/components.md

As per la première bierre française, aka #1664, it's a misleading over simplification to say that component definition properties are 'copied' to instances on initialisation.
I'd thought to write a little addendum with avoid / prefer, but this isn't really an anti pattern so much as a gotcha resulting from the prior miscommunication. Speaking of which, how about an FAQ of common unexpected behaviour? The current format of the docs tempts us to keep adding 'anti pattern' descriptions which make Mithril look forbidding and simultaneously encourage the glossing over of subtle implementation details and viable techniques with simplified dos-and-donts.

Docs: component props aren't copied to instances

---

bundler/bundle.js
bundler/tests/test-bundler.js
stream/stream.js

Building on @nolanlawson's work on [optimize-js](https://github.com/nolanlawson/optimize-js), we measured the Mithril loading times with different types of module wrappers.
The following contenders were evaluated:
- IICE `new function(){}`, where C stands for constructor, the current Mithril wrapper
- IIFE `(function(){}())`, the Crockford-sanctioned syntax.
- BIIFE `!function{}()` where B stands for Bang, popular among punks (and robots?)
Performance was [measured](http://jsbin.com/kizasekuho/1/edit?html,js,output) with `window.performance.now()` (with a fallback to Date.now() for iOS Safari). We used a "three scripts tags per measure" approach to really measure the parse time of the middle one.
```HTML
<script>var start = now()</script>
<script>var iteration = …
```

IICE => IIFE

---

docs/vnodes.md
render/render.js
render/vnode.js

This is the simple proposal described in #1694.
`vnode.state` is not defined by `Vnode` anymore, but by `createNode`, and `updateNode` for recycled components (this fixes a bug in the latter case where the old state would be recycled for non-component nodes).

Let `render()` create the state rather than `vnode()`

---

.travis.yml
docs/CNAME
docs/generate.js

This modifies the existing travis script and changes the flow some so that docs will generate & auto push to the `gh-pages` branch when builds succeed on `master`. 
Was going to use `travis-scripts/update-branch` since it would do this a bit more cleanly but it has no option to preserve files on the target branch which we need for archived versions. So `gh-pages` and some flopping around it is.
**TODO once merged**
**Caveat** I would love to have docs changes to `next` auto-generate docs for another site, something like mithril-next.js.org, but that doesn't seem easy currently. Closest I can get so far is to spend some time figuring out how to get it to build changes on `next` into some sort of `./next` folder in the `gh-pages` branch.
@lhorie verbally (textually?) approved this work [in …

Docs auto-push to gh-pages branch

---

examples/todomvc/todomvc.js

Expected behavior: When edit todo title. If press enter when title is blank. Todo item should delete
Observed behavior: Nothing happen when press enter.
Root Cause. state.update call to destroy instead of state.destroy()
Expected behavior: When edit todo title. If press escape, all change should cancel
Observed behavior: Nothing happen when press escape
Root Cause. input.edit monitor onkeypress event instead of onkeyup event
This PR fixes todomvc to work as expected.

Fix todomvc state.update and ui.save

---

ospec/README.md

and suggest `npm-run` as a workaround.
Counter-proposal to #1547/#1553 where we're piling up brittle fixes on top of one another...

[ospec:docs] Document the fact that ospec doesn't work when installed globally

---

docs/jsx.md

Updates `m.mount(document.body, <MyComponent />)` to `m.render(document.body, <MyComponent />)`.
After consuming a component using `m(component)`, you can't *mount* it to element but you can *render*.

Fixes component usage in jsx.md.

---

docs/route.md

reading the diff for the #1711 fix made me realize that this wasn't documented (@StephanHoyer stumbled on this recently in #1709, but he's not the first)
Also, the docs said incorrectly that `m.route.link` was returning an event handler.

More m.route docs fixes

---

.eslintrc.js
.travis.yml
docs/releasing.md
package.json

They won't have an amazing description or anything, but every time we push a tagged commit to `master` it'll create a Github release.
:warning: **This is really difficult to test outside of the main repo, so there may be some bugs** :warning:
Once it lands I may need to do some futzing to get it fixed up when it's time for the next release.

Automate github release pages

---

docs/stream.md

These hadn't been added yet so I took a stab at it. TBH I'm a bit out of my depth, so I looked at the flyd docs for some help. Their [scan](https://github.com/paldepind/flyd#flydscanfn-acc-stream) docs appear to have typos so I tried to straighten it out. [scanMerge is here](https://github.com/paldepind/flyd/tree/master/module/scanmerge)

Added docs for stream scan and scanMerge

---

.eslintignore
stream/stream.js
stream/tests/test-stream.js

This builds on top of #1737 to fix #1736.
Oddly enough, my local git version is convinced that `stream.stream.js` is a binary file. Thankfully the diff shows fine here.

Fix stream end map

---

stream/tests/test-stream.js

Tests for issue #1736
Any maps set to the end stream do not get called.
In fact, for some reason adding a map to and end stream throws an error:
```
Cannot read property '_state' of undefined
at updateDependency (/Users/eladzlot/www/mithril.js/stream/stream.js:46:20)
```

added test for stream.end.map

---

docs/keys.md

The previous example about hiding keys had syntax errors, and example in itself didn't follow our own guidelines (key should be on immediate child of an array). The example doesn't really solve the problem keys are for because of this. We lose focus on inputs by completely removing dom elements and reinitialize them
In the new example we reuse the code from the previous example but break out a User component (which is much more likely) and the example says to move the key from inside the user component instead
This jsfiddle illustrates the example: https://jsfiddle.net/1snzumk2/1/
It's easier to see that we lose focus on the first one if we change it to a textarea, but press a button to see the effect. the list shuffles every 5 seconds

Improve keys example

---

test-utils/pushStateMock.js
test-utils/tests/test-pushStateMock.js

Make the mock `history.onhashchange` behave closer to the real thing.
This patch only changes `test-utils/pushStateMock.js` and the corresponding test files. Since the mocks support `pushState`, the `onhashchange` mode of the router is apparently never tested (or at least never in ways that differ whether `onhashchange` is synchronous or debounced, async).
This is a prerequisite to fix #1734. Theoretically, the rest of the fix may be independent of #1592 / #1765 but if the tests must be modified in any way, I'd rather wait on at least #1592 to be merged, otherwise conflicts will arise.

[mocks] make location.onhashchange debounced async

---

render/hyperscript.js
render/tests/index.html
render/tests/test-hyperscript.js
render/tests/test-onbeforeremove.js

@tivac Once this is merged, I'd like to release v1.1.1 ASAP, but I'd rather have you around if anything goes wrong...

hyperscript: Revert attrs.class creation logic to what we had in v1.0.1. fix #1764

---

render/tests/test-hyperscript.js

Fix some quotes

---

docs/generate.js
docs/index.md

We keep talking about it, so I went ahead and gave it a shot.
I used codepen because JsBin requires a Pro account to embed HTTPS bins, which is a bummer. The default codepen styling works ok though w/ the site aesthetic IMO.
I made them click-to-load in the interest of not slowing the site down any more than necessary. Here's an example of the embed before clicking
and then after
The pens aren't editable on the page (because that requires a Pro account) but even seeing them up & working seems pretty worthwhile to me.
Thoughts? Should I take this further? I think the homepage is probably the biggest bang for our buck in terms of showing live examples so limited it to that page, but they're simple enough to add to other pages if it's worthwhile.

Add codepen examples for tutorial

---

render/render.js
render/tests/test-input.js

This is an attempt to fix: https://github.com/lhorie/mithril.js/issues/1814
Adds related tests.

Fix select option to use empty string value, add tests.

---

.travis.yml
docs/change-log.md
docs/contributing.md
docs/examples.md
docs/framework-comparison.md
docs/installation.md
docs/layout.html
docs/nav-guides.md
docs/nav-methods.md
docs/releasing.md
docs/simple-application.md
docs/testing.md
ospec/package.json
package.json
stream/package.json

Did a pass to convert all `lhorie/mithril.js` refs into `MithrilJS/mithril.js`. Also all `rewrite` branch references to `master`.

Update all repo references after the great migration

---

render/hyperscript.js
render/tests/test-hyperscript.js

Sending the empty string as the value of an input or option in a selector passed to m() yields a tag with value="true"
e.g.
```m('input[value=""]')``` becomes ```<input value="true">```
and
```m('option[value=""]')``` becomes ```<option value="true">```

selector [value=""] is mishandled

---

render/render.js
render/tests/test-createElement.js

Fixes issue #1819 foreignObject inside SVG

Override namespace with xmlns attribute

---

docs/route.md

I was stuck on this for a while earlier today: it turns out that `m.route.param` will not return the right results in the `onmatch` function on a `RouterResolver`, though it will inside of a `render` function on the same. This behavior is documented in the `onmatch` section but not the `m.route.param` section, which is where I was looking when I ran up against this earlier.
From an API design perspective it would make sense to me for `m.route.param` to return valid results inside `onmatch`, but I don't know enough about Mithril's internals to know how complex it would be to implement.

Improve the documentation of routing parameters

---

ospec/bin/ospec

Motivation: When using ospec on Cloud9, a difficult-to-diagnose error shows up with `SyntaxError: Unexpected token :` because ospec is trying to parse metadata about the tests files (like undo information for working on `tests/hello.js`) that is stored under `.c9/metadata` with the exact same file path and names as the edited files have (e.g. `.c9/metadata/workspace/tests/hello.js`).

Update ospec to ignore hidden directories and files

---

render/tests/test-attributes.js
render/tests/test-component.js
render/tests/test-createElement.js
render/tests/test-event.js
render/tests/test-onbeforeupdate.js
render/tests/test-onupdate.js
render/tests/test-updateElement.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

This is a preliminary PR before I move on with the actual fixes for #1804 and #1595 redux.
The tests commented out are failing, but shouldn't.

Improve mocks and render/tests/test-attributes

---

render/render.js
render/tests/test-attributes.js

Some of this will be simplified when we tackle #1804

Re-fix #1595

---

docs/simple-application.md

`m.request` examples in the simple app tutorial use the URL interpolation feature. This PR removes it so an an extraneous query string isn't appended to the get user request URL . I've also removed it from the save user for consistency. Follows up on: https://github.com/lhorie/mithril.js/issues/1788

Remove url interpolation from tutorial app

---

docs/es6.md
docs/jsx.md

Webpack doesn't support relative paths in the output.path config parameter, so this updated code uses the 'path' module to resolve the relative path.

Use manual path resolution in webpack.config.js

---

api/redraw.js
api/tests/test-mount.js
api/tests/test-router.js

No tests for this since the mocks don't implement event bubbling right now.
I suggest we merge this and leave #1850 open with the "needs test case" label only...

Set event.redraw to true before passing it to event handlers, fixes #1850

---

api/router.js
api/tests/test-router.js

Don't overwrite the options object when redirecting from onmatch with m.route.set

---

stream/stream.js

I'd rather not remove the `stream/stream.js` IIFE for a patch release... @spacejack is this ok for you (for now)?

Temp fix for #1831

---

.travis.yml

According to [the docs](https://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A) both `tags` and `branch` don't make sense, and we only care about tagged commits.
This is prep work for cutting `0.2.6` (and any other future releases in the `0.2.x` line).

Remove unnecessary branch filtering

---

.travis.yml
package.json

`npm@5` changed to save-by-default, which screwed up the plan of keeping travis-only deps out of `package.json`. Remove them entirely from `devDependencies` and ensure that Travis won't accidentally re-add them.
Fixes #1894

Don't add travis-only deps to package.json

---

.eslintignore
.travis.yml
README.md
bundler/cli.js
docs/generate.js
package.json

It's confused me multiple times that `./README.md` was actually `./docs/index.md` but run through a generator. As time has gone on I've become more and more convinced that this wasn't the right choice so this is my stab at fixing that.
The new `./README.md` is much simpler, with styling that fits on GitHub better and makes more sense as a high-level overview of the project. It also should automatically get its gzip size updated on builds again, something that got lost in the distant past (seriously I can't find it on GitHub...) and I would really like to work again.
[Preview the new Readme](https://github.com/tivac/mithril.js/tree/readme-rework#readme)
While trying to verify things I was having ESLint failures on weird folders inside `node_modules`, so I took a look and tweaked the …

Readme rework

---

docs/jsx.md

Adding clarification that babel options can't be included in the `babel-loader` object of your `webpack.config.js`, for silly people like me who sometimes don't follow directions

Clarifying babel/webpack docs

---

docs/change-log.md

I couldn't find an issue matching this commit: [Update style attribute if it is a mutated object](https://github.com/lhorie/mithril.js/commit/474c43e433eecb4d129918769af95468a22152e9) maybe it was raised on gitter?
**Other easy candidates for `v0.2.6`:**
- ~~a fix for an edge case w/ contenteditable & m.trust #900 _(provided conflicts are resolved, I can do it)_~~ DONE
- fix finding current target parent link in routeUnobtrusive #1009 _(after careful review, since I don't think it is possible to test it)_
- Unmount cleanup (#727 regression) #1289 _(rebased, CI passed)_
**May need more work**
- ~~update Select2 integration example and explanation #1028 _(needs at least a rebase and an indentation fix + editorial review)_~~ DONE
- Add typings to distribution #1012 _(TypeScript-related, I'm …

[next] Update change log

---

docs/change-log.md
docs/mount.md
docs/redraw.md

Docs for async redraws and assorted changes (see #1592)

---

request/request.js
request/tests/test-request.js

So that there's no chance of data loss and it's trivial to get the response code (because it's hella useful!)
Fixes #1866
Fixes #1876

XHR errors have response/code fields

---

package.json

No end-user needs it, it's solely for mithril development. Also causes problems for some folks.
Fixes #1668

Remove bundle bin

---

.travis.yml
package-lock.json
package.json

After more discussion in #1909 we decided that `prettier` wasn't the right approach, but `eslint --fix` is definitely a good idea. Reducing the likelihood of bad code in PRs is always a win.
This also standardizes on all packages in `package.json`, previously there were a few that were only installed on travis-ci. I never liked that approach though, so I'm getting rid of it.
Automatically fixing simple formatting errors before submission!
Tested writing some bad code, then committing it & comparing the diffs.

Run eslint --fix against commits

---

.gitattributes

Modified the .gitattributes so that lock files don't show often noisy, useless diffs every time they're updated. It's pretty self-explanatory.
I included Yarn's `yarn.lock` as well, in case that file ever finds its way into our repo (likely by my own unconscious doing).

Don't show diffs for package lock files

---

docs/route.md

This is just a simple documentation fix for those who copy/paste examples to test basic functionality.  There was a missing `}` that caused a syntax error.

Fix mismatched brace in Authentication example

---

render.html

Found a small typo in the documentation, hopefully this is the right way to edit it. Thanks for the awesome library!

Fix small typo in render.html

---

docs/change-log.md
request/request.js
test-utils/tests/test-xhrMock.js
test-utils/xhrMock.js

Fix Content-Type header bug (Issue #1919)

---

docs/change-log.md
render/render.js
render/tests/test-updateElement.js

This change attempts to partially improve on style object diffs (See: https://github.com/MithrilJS/mithril.js/issues/1932)
This change only takes effect when a fresh style object is provided each render. If a cached style object is used, then the behaviour remains unchanged (all element style properties will be wiped and re-rendered.)
Since `attrs` objects are not cloned, it's not easy to keep a copy of the style object used for the previous render. Furthermore, since [undesirable behaviour](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcIB0ArMIA0IAZgJYy6oDaoAdgIYC2EamAFvPVPiLAPbWL9mIAL54aDJumy4CvfhEHo5YeAAIATjx5qAvKqQ9YAV0b8MAIx5IAngB1q9mGtrx46sKr3AV1mKlUA5LxQPOr+AMQAYgAM0QHC9vb0GOoKSBDqABSa2nj2qqr0mQEBeKoubmBltiAASsg1AJT2zQ50ru4YPjCegcGhEdExAfYA9KMV7r3e8L4Q-kE8IWGq4UNxCW3jqgDKLDxGUEiq5hCqAOapCm …

More accurate style object diffs

---

docs/change-log.md
render/hyperscript.js
render/tests/test-hyperscript.js

Possible fix for **Shared attributes for different component results in concatenated class names** #1941 
Mithril modifies passed attributes object to store classname derived from selector. I suggest we make a copy so there will no unexpected side-effects. 
btw, I'm using custom shallow copy instead of `Object.assign` because mithril seems to support IE9 and 10. Is it still the case?

Handle shared attributes object in hyperscript

---

docs/change-log.md
render/render.js

There is an issue in IE where `document.activeElement` becomes null sometimes. For example when you [use `removeChild` to remove an element, the active element isn't reset](https://stackoverflow.com/questions/36008978/document-activeelement-is-null-in-internet-explorer). And sometimes in [iframes](https://www.tjvantoll.com/2013/08/30/bugs-with-document-activeelement-in-internet-explorer/).
When this happens using mithril, the render function throws an error on [line 633](https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L633).
This is an issue that has come up in other frameworks, [for example in Angular](https://github.com/angular/material2/issues/2760).
In my case, I have a click event that removes an element that has an `onremove` function. That `onremove` function …

Fixing IE bug causing active element to be null causing render function to error

---

performance/test-perf.js

We special-case identical vnode trees, so it's better that we test both
identical and rebuilt trees when benchmarking rendering.
Internally, we skip rendering when we re-render identical vnode trees, and we also recommend that people *not* cache vnode trees for obvious reasons.
For similar reasons, I added a new benchmark to test the (exceedingly common) case of completely static, newly rebuilt trees. The copied test features a single event handler, attributes, and some `style` modifications, so it also lends itself well to benchmarking other aspects of the diffing algorithm.
Re-ran the benchmarks right after the change, as you might expect.

Make the benchmark a little more precise

---

docs/change-log.md
ospec/README.md
ospec/ospec.js
ospec/tests/test-ospec.js
promise/tests/test-promise.js

Support promise returns in ospec as alternative to `done` callback. Also supports `async/await` automatically
Currently ospec does not support returning promises or using `async/await` without wrapper. This PR tries to add support for that.
async/await is the future for async stuff. We should support this.
* Wrote a test that verifies basic usage
* checkt if timeouts work

support promise return in ospec

---

docs/change-log.md
ospec/ospec.js

Use util.inspect if available to do better logging of objects
Mainly deepEquals on objects just prints [object Object] instead of the contents, making it hard to see the possible error.
Tested by visually inspecting the output which looked correct.

Use util.inspect to log in node - fixes #1661

---

docs/jsx.md

Change tag name from `div` to `a` in jsx example and add end parenthesis.

[docs] Fix typo in jsx docs

---

docs/simple-application.md

Adds "missing" file path comments to tutorial.
As the other code snippets include file path, maybe these two should too.

Consistent file path comments to tutorial

---

docs/style.css

Fix for #1973
>Looking at https://mithril.js.org/api.html i think i came across a z-index issue on the mobile media query. The open menu appears behind content, setting it to anything greater than 0 fixes it.

Fix menu css z-index

---

docs/change-log.md
render/render.js
render/tests/test-attributes.js
render/tests/test-createElement.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

Just noticed while playing around with some optimization that `xlink:*` attributes were being mishandled, but I also noticed that `option.value` was incorrect in the mock, so I fixed it.
Added some new tests and ran them all as usual.

Allow `xlink:href` to get removed, fix `option.value` in mock

---

docs/change-log.md
render/render.js
render/tests/test-input.js

Changing focus on element creation and update is currently no possible even if intended. The original activeElement is restored after rendering, because of some issues with rendering in IE according to the comments: https://github.com/MithrilJS/mithril.js/blob/next/render/render.js#L668-L669
There is a valid use case for changing the behavior. Let's assume we have a modal (might come from 3rd party library) that sets the focus to inner input when shown. When closed it resets the focus to original active element.
```js
function openModal(node) {
renderModal(node);
previousActiveElement = document.activeElement;
input.focus();
}
function closeModal() {
previousActiveElement.focus();
}
const modal = () => 
<Modal oncreate={({dom}) => openModal(dom)}>
<Input id="input"/>
</Modal>
render(root, …
```

Allow for changing focus in lifecycle hooks

---

docs/route.md

#2002 
While the docs do say that a second render pass for preloaded data comes
from request completion, the example code for preloading data suggests that
a promise chain returned from `oninit` has a role to play in controlling the
second render pass.
The docs should make explicit where the redraw is initiated so the reader
does not mistakingly believe that `oninit()` retuning a promise changes
anything.

Clarify source of 2nd render pass re: preloading data

---

.eslintrc.js
ospec/ospec.js
ospec/tests/test-ospec.js

ospec needs global-require suppressed so it can use `require('util')`.
~~test-ospec needs `ecmaVersion: 2017` so it can use `async`/`await`.~~
Removed async/await from test-ospec; just return Promise instead.
Modified `ospec.js`, `test-ospec.js`
Mithril's test script linting was failing.
`npm test` now succeeds without errors.

Update eslint rules for ospec

---

docs/change-log.md
ospec/ospec.js
ospec/tests/test-ospec.js

Moves an inline `match` call into its own function (`o.fn` level), adds a failing test to that function, then fixes its behavior.
Fixes #1495 
Created a new function, ran `node ospec/bin/ospec` on it
- [~] My code follows the code style of this project.

Handle newlines in error messages, fixes #1495

---

bundler/minify.js

Closure compiler endpoint was returning a `302` since we were using HTTP and it now requires HTTPS. So now using the `https` module instead of the `http` module for communication.
Fixes #2005 
`npm run minify`

fix: closure compiler requires HTTPS now

---

api/router.js
api/tests/test-router.js
docs/change-log.md
docs/route.md

Some refactoring to enable passing the `options` object to `m.route.set` using the `m.route.link` API in lifecycle methods.
With current functionality, there is no way to overwrite browser history entries and pass specific parameters to the history API with `m.route.link`, this always requires a custom method to be written.
Related issues #1807 #1810 
`npm t` with new test case.

Enable setting navigation options with m.route.link API

---

docs/change-log.md
docs/request.md
request/request.js
request/tests/test-request.js

Changes to accommodate #2000.
`m.request` will no longer reject the Promise if the caller supplies an `extract` callback.
See #2000 
Test added.

Don't reject m.request Promise if extract callback supplied

---

docs/change-log.md
docs/request.md
request/request.js
request/tests/test-request.js

Add support for `timeout` to `m.request`.
I think it's obvious that `timeout` is a thing you want to set to an xhr.
Added a test that verifies xhr setting

Add support for `timeout` to `m.request`

---

docs/change-log.md
ospec/README.md
ospec/ospec.js
ospec/tests/test-ospec.js

Valiantly defy one bullet in the ospec goal of blocking test configuration by adding custom reporter support. :crown:
See #2019
I added a `reporter` param to `o.run()` to allow custom processing of results, falling back to current behavior if one is not specified.
ospec absolutely should limit test space config, but not having this feature has severely limited my ability to pass results along to a CI system when running ospec in a browser or Node.js. This change in made with the intent to leverage the entire Mithril toolset for real-world systems.
I used `o.new()` to make a new `ospec` runner, and then used the clone's custom reporter to run assertions against the original `ospec` instance. So if the reporting did not work, `test-ospec.js` would fail.

feat(ospec): Allow custom reporters for CI reasons (#2019)

---

docs/style.css

Fix headings displaying over menu on mobile, applying a z-index:1 on the CSS rule of the menu element.

[docs] Fix headings displaying over menu on mobile

---

promise/tests/test-promise.js

`ospec` changed to support `done(err)` in 39be9134f94f78da635a6ad86d1722f047326c01 and that broke a test. This fixes it.
`master` was broken.
`npm test`, all tests passed.
PS we have a few lint errors that nobody caught because they don't break builds. Maybe they should?

test: fix broken test after ospec update

---

docs/style.css

fix css typo- `bakground` should be `background`
`bakground` is not a valid css property.
Verified that only `background` works (Chrome latest).

fix typo in body background style

---

docs/change-log.md
ospec/README.md
ospec/ospec.js
ospec/tests/test-ospec.js

There are a few annoyances when using Ospec in Flems:
1) It only works in CommonJS environments
2) It uses console.error, which in Flems prints out the full stack trace (which can be long in Ospec thanks to nextTickish)
3) It expects to find its own file name in the path (to clean up stack traces), but Flems only provides a hash, that's more of a Flems issue probably.
This fixes 1 and 2
edit: and now 3, and also #2036

Make Ospec Flems-friendly

---

docs/change-log.md
render/render.js
render/tests/test-onremove.js
render/tests/test-updateNodes.js

Edit: this is done AFAICT
Fix for #1990, #1991 and #2003
The logic in updateNodes will still need some love for fragments (the last commit is actually sub-optimal, skipping `insertNode` when the vnode is a fragment would be better since the children of the fragment will have been inserted at that point. That's a change for tomorrow though.
Few lines of `updateNodes` are left untouched. Hopefully the individual commits will make the review easier.
No formal review requested now since there will be future changes. If @starsolaris  and @purplecode want to test the waters, there's a build at https://github.com/pygy/mithril.js/blob/fix-updateNodes-build/mithril.js
So far, mostly manually in Flems, I'll have to cook up test cases. There were quite a few bugs.

Fix updateNodes() (mostly vdom diffing logic).

---

docs/change-log.md
render/render.js

I wanted to make sure that the changes I'm making to updateNodes don't have a negative impact on benchmarks and noticed a stark perf regression in the `next` branch when compared to `v1.1.6`. It turns out that checking `parentNode` happens to be toxic. Since #1916 was about `select`/`option`, I've limited the check to `option` elements.
as little as #1918 since the mocks still don't support the correct API.

render: fix perf regression introduced by #1918

---

docs/installation.md

Added notes about installing TypeScript types to the install.md page.
I also thought for clarity it'd be nice to break out a separate section for npm installation. I realize it's pretty obvious, but I think it's good to have that front and centre rather than burying it within the webpack walkthrough. TOC has been adjusted accordingly
https://github.com/MithrilJS/mithril.js/issues/1985

Add Typescript install notes

---

docs/route.md

The default URL supplied in the current docs for variadic paths `/edit/pictures/image.jpg` does not match the router path starting with `/files/:file...`:
```
m.route(document.body, "/edit/pictures/image.jpg", {
"/files/:file...": Edit,
})
```
This changes the router path to match the "Edit" idea of the example, resulting in:
```
m.route(document.body, "/edit/pictures/image.jpg", {
"/edit/:file...": Edit,
})
```
Related test:
https://github.com/MithrilJS/mithril.js/blob/next/router/tests/test-defineRoutes.js#L116-L117
This PR is an update for this prior PR changing the derived html file and not the md file: https://github.com/MithrilJS/mithril.js/pull/2081

docs: Fix inconsistent path in router.md variadic routes example

---

docs/change-log.md
render/render.js
render/tests/manual/iframe.html
render/tests/manual/iframe.js
render/tests/manual/index.html

Accessing `document.activeElement` when inside an iframe throws an error for Internet Explorer versions 9 through 11 (at least). Catch this error and return `document.body` instead in these cases. I'm not sure what the ramifications are of returning `document.body` but I'm happy to update with any suggested changes.
While mithril apps work in these versions of IE, they'll break when inside an iframe without this fix.
Built locally with `npm run dev` and ran the `render/tests/index.html` and `tests/index.html` tests and saw zero assertion failures.
(two tests fail, actually, but they fail in `v1_1_x` as well: `test-jsonp.js:80` and `test-request.js:322`)

Access document.activeElement through a function that eats errors for IE

---

docs/installation.md

- Add `webpack-cli`
- Fix usage to include `--output` flag
- Make default use `-d` for debug builds
Came up as part of #2093 but that contained a band-aid docs fix, this fixes the underlying webpack misuse.
Ran through the steps locally in a new folder and verified that it worked

docs: correct some webpack bitrot

---

docs/change-log.md
performance/test-perf.js
render/render.js
render/tests/test-component.js
render/tests/test-onbeforeupdate.js
render/tests/test-onremove.js
render/tests/test-updateElement.js
render/tests/test-updateNodes.js

This is an alternative to #1675 which removes the recycling pool altogether. I couldn't find the time to properly benchmark the change, but other libs (among the fastest ones) have dropped that approach since it didn't bring them any significant advantage.
The pool makes the whole `render/render.js` more complex. Having it out for now should make other needed changes easier (like, the longest increasing subsequence code to be lifted from Ivi).
I've left the tests in place (with some modification to assert that nodes are not recycled). If we decide to commit to this approach in the long run we can remove them too (I'd rather keep them in for now).
Edit: like #1675, this also fixes #1653 and #2023 that were purely caused by the existence of the pool.
Edit2: I also removed the corresponding …

Remove the DOM nodes recycling pool

---

docs/installation.md
docs/integrating-libs.md
docs/learning-mithril.md
docs/nav-guides.md
docs/route.md
docs/support.md

Getting ready to publish the updates to fix the weirdness I mentioned in #2199

docs: latest site updates

---

bundler/tests/test-bundler.js

Discovered while testing #2133 
```
> cd mithril.js
> node ospec/bin/ospec
1 assertions completed in 95ms, of which 0 failed
7992 assertions completed in 1730ms, of which 0 failed
> cd bundler
> node ../ospec/bin/ospec
bundler > relative imports works:
ENOENT: no such file or directory, open 'bundler/tests/a.js'
at Object.fs.openSync (fs.js:646:18)
bundler > relative imports works with semicolons:
ENOENT: no such file or directory, open 'bundler/tests/a.js'
at Object.fs.openSync (fs.js:646:18)
[...]
31 assertions completed in 20ms, of which 31 failed
```
From the command line
```
> cd mithril.js/bundler
> node ../ospec/bin/ospec
31 assertions completed in 240ms, of which 0 failed
```

fix: Bundler tests only pass when run from project root

---

docs/vnodes.md

URL was being incorrectly parsed due to parentheses. The parenthesis have been replaced with UTF-8 encodings.
Fixed URL for Wikipedia entry to Immediate Mode
The link was broken
I clicked the link in preview mode

Fix url in vnodes.md

---

docs/stream.md
stream/stream.js
stream/tests/test-scan.js

Description
------------
If the reducer function doesn't change the value, then don't call the dependant streams.
Motivation and Context
-----------------------
Example use case:
```javascript
var dispatch = Stream()
var store = Stream.scan(update, init(), dispatch)
function update(store, {type, value}) {
switch (type) {
case UNDO:
return undo(store) // if nothing to undo, then return `store` (= HALT).
case REDO:
return redo(store)
case INSERT:
return insert(store, value)
case FLUSH:
return init() // creates an empty undo history
default:
return store // shouldn't trigger update
}
}
```
Equally, if `scan` accepted the `HALT` value, then I could get the desired effect with a higher-order reducer:
```javascript
function wrapReducer(reducer) {
return function (state, action) {
var next = …
```

Scan with halt

---

docs/change-log.md
ospec/change-log.md

On suggestion by @pygy in #2138, I added a "change-log.md" file and moved all ospec related improvements lines from "mithril/docs/change-log.md" into it.
**However**, most of ospec's history is dark mystery, and even the commits/issues leading up to v1.4.1 are pretty opaque - as ospec/package.json is still stuck at 1.4.0 and... you know. Bah
So I'm not going to take this attempt any further, and leave it up to you guys to provide the remaining info.

Ospec changelog

---

ospec/README.md
ospec/bin/ospec
ospec/package.json
package.json

Feel free to ignore this pull request.
Its sole purpose is to illustrate what an alternative approach to #2137 and #2133 could look like – if only ospec was treated like a first-class package allowing a single dependency for the node.js binary.
Point being, that the CLI binary is hardly ever used unless installed via npm (or yarn) which install the dependency automatically - while ospec the JavaScript module could still be copied around and loaded in browsers without any need for an external dependency.
FWIW: If this PR gets rejected, then I'll publish this binary as a separate npm module, having ospec as its dependency to allow people like me to add a single testing module to their project and not worry about installing separate globbers, like glob-cli, and piping to ospec via stdin... …

Ospec: nicer binary with support for globs

---

ospec/bin/ospec

My bad. #2141 was broken when merged
Multiple globs, caused multiple calls to `o.run()` so some of the tests were run multiple times.

fix(ospec): Only run o.run() once

---

ospec/change-log.md
ospec/ospec.js

Colored output was up to this point unconditional...

[ospec] don't output colors when pipe or file redirection is used

---

ospec/README.md
ospec/bin/ospec
ospec/change-log.md

I'm using [esm](https://www.npmjs.com/package/esm) to enable ES Module support on node.js. I mimicked the logic from [tape's executable](https://github.com/substack/tape/blob/master/bin/tape#L20-L26). Example usage:
ospec --require esm
This PR also allows requiring local files, so it should prove to be a flexible addition (e.g. requiring a file that injects global test helpers).
I'm using it in one of my projects and it works.

Add --require feature to ospec executable

---

render/hyperscript.js

No functional change. I read code and noticed it.
Minor. Feel free to pull or not.
Locally.
Optimization.

Small optimization in render hyperscript.js

---

docs/change-log.md
ospec/README.md
ospec/change-log.md
ospec/ospec.js

I thought the default reporter could be made to look nicer, using more colors, a divider and slight indenting of the `verb` ("should equals" etc) and some rewording of the final result message.
**Browser:**
**Update:** See **[below comment with updated screenshots](https://github.com/MithrilJS/mithril.js/pull/2147#issuecomment-388315182)**
**Browser:**
Ran tests in node and pasted representative `console.log` and `console.error`strings into the developer console of Chrome and Firefox. (See screenshots below.)

[ospec] Make the default reporting nicer looking

---

ospec/change-log.md
ospec/ospec.js

This adds a cleaned up stack trace after the `o.only()` warning.
I'll update the change log once #2147 is merged
Makes it easier to find the place you added that `.only()` call.
Manually

[ospec] pinpoint the o.only() call site

---

ospec/bin/ospec
ospec/change-log.md

Fix #2160 by reverting to ES5 syntax
`npm run test` works as usual.

[ospec/bin] Back to ES5 (and complimentary cleanup)

---

ospec/ospec.js

Ospec is crashing in one of my projects when the stack returns `-1` for *all* invocations of `.indexOf(ospecFileName)`. This causes `i` to eventually increment past the length of the array and spit out the following error:
```
TypeError: Cannot read property 'indexOf' of undefined
at Function.o.cleanStackTrace (./node_modules/ospec/ospec.js:70:19)
at Function.o.report (./node_modules/ospec/ospec.js:269:24)
at Timeout._onTimeout (./node_modules/ospec/ospec.js:81:23)
at ontimeout (timers.js:482:11)
at tryOnTimeout (timers.js:317:5)
at Timer.listOnTimeout (timers.js:277:5)
```
This change prevents this from happening, spitting out the true error from the test failure instead.

Fix stack trace edge case

---

docs/change-log.md
render/render.js
render/tests/test-updateNodes.js
render/tests/test-updateNodesFuzzer.js
render/vnode.js
test-utils/domMock.js

This has been a long time coming. This changes the core keyed diff algo as follows.
Previously we were
1) traversing the list top down as long as keyed were matching
2) moving nodes from top to bottom if the top of the old list matched the end of the new one (list reversal)
3) traversing both lists bottom-up as long as the keys match
4) creating a `{[key]: index}` map for the old list, and using it to match old and new nodes when the order was scrambled.
This was sometimes causing unneeded DOM node moves.
This PR takes a page from [ivi](https://github.com/localvoid/ivi/blob/e933fbef767961382c6d8c87c33679005fba08ba/packages/ivi/src/vdom/implementation.ts#L637-L863) and changes the way step 2 and 4 work.
Now we first perform step 1 and 3. 
Then we do symmetric swaps (asymetric ones as we …

Introduce longest increasing subsequence-based node moves in keyed diff

---

docs/change-log.md
docs/lint.js
ospec/ospec.js
performance/test-perf.js
render/render.js
render/tests/test-attributes.js
render/tests/test-createElement.js
render/tests/test-updateElement.js
render/tests/test-updateNodesFuzzer.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

This fixes #1804 and tweaks #1595.
`removeAttr()` now mirrors `setAttr()`. values set to `undefined` or `null` are equivalent to a lack of value, except for `select`, where `null` 
There are still possibly problematic corner cases with `select.value`, please don't merge this yet.
#1862 can be merged as is in the mean time if you want. I'll rebase this.

[WIP, don't merge] Fix #1804 and tweak #1595

---

docs/change-log.md
docs/hyperscript.md
performance/index.html
performance/test-perf.js
render/hyperscript.js
render/tests/test-hyperscript.js
render/tests/test-render-hyperscript-integration.js

This makes the `attrs` take precedence over the selector (#2172), and improves class normalization (#1773).
The docs and change log will follow here.
See the respective issues for a detailed discussion.
`m("[a=b]", {a: "c"})` will now have `a` set to `"c"`, and `m("[a=b]", {a: null})` will have it set to `null` (likewise for `undefined`).
regarding classes: 
- `m(".foo", {}).attrs` will be `{className: "foo"}`
- `m(".foo", {className: "bar"}).attrs` will be `{className: "foo bar"}`
- `m(".foo", {class: "bar"}).attrs` will be `{class: "foo bar"}` (we re-use the `class` field if users chose it. Leo said it was slower, but I didn't see any difference in the benchmark)
- `m(".foo", {class: false})`,  `m(".foo", {class: null})` and `m(".foo", {class: undefined})` all behave as if there was no …

Hyperscript: fix #1773, fix #2172

---

render/render.js

Simple fix for #1983 using @pygy's recommended code. I ran into this bug myself and did not see any open PRs fixing it.
See description here: https://github.com/MithrilJS/mithril.js/issues/1983
Fixes #1983 
Ran `npm test` and also tried the updated code in Chrome/FF/IE11

Prevent activeElement.focus on SVGs, fix #1983

---

docs/installation.md

Replace webpack example with one that uses parcel. It's much simpler.
There was an issue of a user in the gitter where (s)he wasn't able to get the webpack thing started. I recommend using parcel and it went smoothly.
yep, just followed the instructions and it worked like a charm.

Use parcel instead of webpack for quickstart.

---

docs/animation.md

Update `onbeforeremove` animation example to use `animationend` event
The example uses `setTimeout()` to time resolve the `onbeforeremove` life cycle method. This PR updates the example, resolving the returned promise when the animationend event is fired.
This change is not required, but provides a better solution. The current example requires matching the CSS animation duration with the timeout. The updated example removes that requirement by using `animationend` event.
Here's a working example using code copied unaltered from animation.md
https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4AbhgBOAAnrSAvNOKSArjAA6aTRJkAVWgHMDsGYuCb1xMRBgB3RNLAq01YhHoAKAJTTzW4paSMMQqkmjSyBYB0Vge6iAARirExPTxFL701FAQ1ADWDk4ubp4+wHKKAIT0rOzS8fpGsPFeFFGWlnIA-NKxAGIYLgCeAM …

Update onbeforeremove animation example to use animationend event

---

ospec/package.json

The glob dependency was moved from `devDependencies` to `dependencies`
To allow installation of ospec properly using npm. Before this change, either `glob` had to be installed manually, or npm would throw the error `Cannot find module 'glob'`
Haven't tested

Fix glob inclusion on npm install

---

docs/change-log.md
request/request.js
request/tests/test-request.js

Currently, when response JSON is not parsed successfully and an error is raised, the error message only contains the response body.
This is unnecessarily cryptic. As someone using the new request implementation for the first time, I was confused as to why just an error "foo" was raised when I was testing a new endpoint.
Relevant test updated.

[request] Clearer error message for JSON deserialization failure

---

docs/change-log.md
stream/stream.js
stream/tests/test-stream.js

When a stream returns halt it is unregistrered to avoid calling dependent streams
https://github.com/MithrilJS/mithril.js/issues/1714

Fix #1714 conditionally halting stream

---

docs/change-log.md
docs/hyperscript.md
ospec/README.md
ospec/change-log.md
ospec/ospec.js
ospec/tests/test-ospec.js
render/render.js
render/tests/test-attributes.js
render/tests/test-hyperscript.js

Align custom elements to work just like normal elements, minus our HTML workarounds. Previously, our support has been undocumented and completely untested, but I plan to fix that in a follow-up commit (along with a changelog entry).
Drive-by: add a `spy.calls` property to ospec that helped me develop the patch. It's technically unnecessary, but it helped me clean up the tests some, and it made the tests a little more concise.
Fixes #2220 
Ran the tests in ospec + Node. Performance changes are within the margin of error, although I made a few size-related optimizations that incidentally reclaimed 33 bytes.

Custom element fix

---

docs/change-log.md
render/render.js

Just a minor simplification of how elements are removed. It doesn't noticeably change performance, but it saves a few gzip'd bytes, and it avoids a function that was only really used for that one thing.
It just cleans up the code some.
Ran all the unit tests and perf tests to check for regressions in both. Performance changes appear statistically insignificant.

Simplify component removal

---

docs/change-log.md
render/render.js
render/tests/test-updateNodes.js

This way, the diff algorithm works with untrusted keys.
Added a new unit test for this subtle key bug.

Avoid triggering `Object.prototype.__proto__` with keys

---

docs/hyperscript.md

Added notes about using EventListener objects, as well as preventing auto-redraw.
Document new features in v2, add needed docs for redraw prevention.

Add docs about using EventListener objects

---

docs/change-log.md
docs/components.md

Remove the "Avoid Restrictive Interfaces" section
See discussion in #2250 and #1986 for more details.
Fixes #1986 
N/A

Remove a section that's 1. buggy and 2. controversial

---

docs/change-log.md
render/render.js
render/tests/test-render.js

Ensures that vnodes are normalized before being stored in the dom element (in `m.render()`).
Fixes #2264
Existing tests pass, added tests to cover this case.

Store normalized vnodes in the dom element. Add render tests.

---

docs/change-log.md

Changelogs for 1.1.4, 1.1.5 and 1.1.6 were there twice. This fixes that.
They should only be there once.
I read it the way it was, and then I read it the new-and-improved way. I like the new way better.

remove redundant changelogs for 1.1.4-6

---

docs/api.md
docs/change-log.md
docs/nav-methods.md
docs/prop.md
index.js
util/prop.js
util/tests/index.html
util/tests/test-prop.js

Exactly what it says on the tin, but I added the `.get`/`.set` version proposed in [this comment](https://github.com/MithrilJS/mithril.js/issues/2095#issuecomment-370099418)
In addition to what was proposed there, I also added `.toJSON` as an alias for `.get`.
Fixes #2095
Added a test just to make sure it works. (I'm not fully convinced it was worth the time to write and run the test, though.)

Add `m.prop`

---

docs/route.md

Add example on how to use m.route.set with params
I had to try a few things before I learned that I needed to define the route, makes sense but couldn't find an example for it

Add example for m.route.set with params

---

docs/autoredraw.md
docs/change-log.md
docs/components.md
docs/hyperscript.md
docs/lifecycle-methods.md
docs/prop.md

This PR prioritizes Closure Components in docs about components with state. It also rewrites examples with component state to use closure components instead of POJOs.
#2291

Docs - prioritize closure components for state

---

docs/change-log.md
render/render.js
render/tests/test-event.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

This is *super* subtle, and IMHO Chrome did exactly the wrong thing here. I have *no* clue why Chrome decided it was a good idea to dispatch the event *after* removal but *before* dereferencing the child from the parent. Couldn't they just remove the child and fire a new event type that contains both the child *and* parent? 😖 
Fixes #1771.
Added some new DOM mocks to align with Chrome and some relevant tests for both this and the new mock behavior.

Fix #1771 and probably others

---

docs/components.md

Fixes #2293, for v2 scope. Mostly just re-arranged the document flow, and special-cased ES6 classes.
Clarity on this doc has been severely lacking. I think this is simpler to understand, without omitting anything.

Component docs update: an effective compromise re: state & syntactic variance

---

docs/vnodes.md

Changed a link to Wikipedia with a misplaced closing parentheses
The link was broken and caused a redirect to Wikipedia search.
```
$ npm run gendocs
$ firefox dist/vnodes.html
```
Verified the link is now working as expected.

Fix parentheses in link

---

ospec/README.md
ospec/change-log.md
ospec/ospec.js
ospec/tests/test-ospec.js

This adds two assertions to Ospec:
- o(Function).throws(Object)
- o(Function).notThrows(Object)
These assertions test whether the provided Function throws the correct type of Error. For example:
```
o(function(){"ayy".foo()}).throws(TypeError)
```
**Edit (isiahmeadows):** Fixes #2146
At present, the only way to use ospec to test whether something throws/doesn't throw an error is something like the following:
```
let error
try{
/* bad code*/
}catch(e){
error = e
}finally{
o(error.constructor).equals(Error)
}
```
Robust applications often have custom error reporting. Ospec would benefit from eliminating the need for developers to include this try/catch boilerplate when testing error reporting.
Tested by running `npm test`, and running the Ospec tests specifically in the browser. This should …

Add 'throws'/'notThrows' assertion to Ospec for error reporting

---

docs/change-log.md
ospec/README.md
ospec/change-log.md
ospec/ospec.js
ospec/tests/test-ospec.js

Previously only failing test results had .message and .context.
This adds .message and .context to passing test results as well, so a complete summary of all test results can be printed if desired.
When reviewing releases, etc, especially with non-developers, it is helpful to be able to explicitly show all test results, including for tests that have passed.
Added 2 tests to Ospec to ensure .message and .context are in both passing and failing test results. Ran Ospec. All tests passed.

Ospec: expose messages for passing tests, in addition to failing tests

---

docs/change-log.md
render/hyperscript.js
render/tests/test-hyperscript.js

When mithril normalizes classNames it now ensures toString is called before concatenating strings. This ensures mithril works like the browser does when setting `dom.className =`. The browser always calls toString for either `dom.classList.add()` or `dom.className =`
This makes mithril behave more like the dom, and allows bss (and maybe others) to support casting to a className using a period when doing 
```
m('div' + b('background blue')) => m('div.bssClass')
```
and not adding a period when doing
```
m('div', { class: b('background blue') }) => m('div', { class: 'bssClass' })
```
[flems with fixed mithril](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J4s+AE5MAJjAkAKabWoBXHA3wAjWtICeFADpoABMazyA5IQCMF4wGpjmgAZHTpzdWNTpb484pjYD9TaigMODhEJ1cTd1MwO …

Cast className using toString

---

render/render.js
render/tests/test-createElement.js
test-utils/domMock.js

Just noticed the fix for css vars https://github.com/MithrilJS/mithril.js/pull/2308 wouldn't support uppercase characters. This fixes it.

Allow css vars with uppercase characters

---

README.md
api/redraw.js
api/tests/test-redraw.js
docs/change-log.md
docs/contributing.md
docs/index.md
docs/lint.js
docs/redraw.md
docs/route.md
module/module.js
ospec/tests/test-ospec.js
render/render.js
request/tests/test-request.js
test-utils/domMock.js
test-utils/tests/test-components.js
test-utils/tests/test-domMock.js
tests/test-api.js

- I also fixed a bunch of related comments
- I had to polyfill `requestAnimationFrame` for Node
- Drive-by: run `eslint . --fix`
- Drive-by: update transpiling info in CONTRIBUTING.md
- Drive-by: we aren't the only ones going semicolon-free
Spurred by some recent Gitter discussion: https://gitter.im/mithriljs/mithril.js?at=5beb8483fee6703aaf68b18b
N/A: the only functional code change wasn't specifically tested for anyways.

Officially drop IE9-10 support, pull out our hacks

---

docs/change-log.md
docs/components.md

**Edit:** update per current patch.
Basically added a bunch of new docs to clarify 1. how to *correctly* avoid restrictive interfaces, and 2. why the obvious is also wrong. I added the known issues people had with lifecycle hooks and I touched a little on better component design.
Fixes #1775
Fixes #1986
N/A - it's docs-only

Fix docs bug, advise against reusing `vnode.attrs` itself

---

.gitattributes
docs/change-log.md
docs/fragment.md
docs/hyperscript.md
render/fragment.js
render/hyperscript.js
render/hyperscriptVnode.js
render/tests/test-fragment.js

Basically, same idea as #2327, done almost at the same time. 😄 
See #2327 - it includes a better writeup than this.
**Edit:** Fixes #2275.
**Edit:** Closes #2327.
Added new tests, ran existing ones.

Allow variadic arguments to `m.fragment`

---

render/hyperscript.js
render/tests/test-fragment.js

Handles `[` fragment selector.
Fixes [2349](https://github.com/MithrilJS/mithril.js/issues/2349).

Handle `[` fragment selector. Fixes #2349

---

stream/stream.js
stream/tests/test-scan.js

Fixes an issue with scan that arose from #2207. The reducer no longer accepted SKIP value as a way of limiting child updates, instead the accumulator value became "SKIP".
For more context see my original change: https://github.com/MithrilJS/mithril.js/pull/1957. The test I added wasn't sufficient to catch breaking change, that is also fixed in this PR! :)

Fixed scan with skip

---

docs/route.md

Replaced semicolon with comma... just a little typo.

Fixed documentation example (typo)

---

README.md
docs/index.md
docs/installation.md
docs/stream.md

- consistently use `@next` and explicit path in unpkg links
- replaced old rawgit link with unpkg link
- updated jsdelivr link on readme to use `@next`
Fix broken unpkg link in stream docs, and standardize the rest.
[Motivated by this gitter discussion](https://gitter.im/mithriljs/mithril.js?at=5cebd81aef853135c830235a).
hand tested

standardize cdn links in docs

---

docs/api.md
docs/index.md
docs/jsonp.md
docs/promise.md
docs/request.md
docs/route.md
docs/simple-application.md

- Replaced request.data with request.body.
- Added request.params to the signature table.
- Where request.data was used for querystring interpolation, I've used request.params.
- serialize uses body too
- replaced hard tabs with double spaces, so the markdown linter is happy.
This is suppose to fix #2423, m.request documentation.
Not
- [] My change requires a change to the documentation.

Fix for #2423. request.data => body, params is used for querystrings

---

docs/change-log.md
request/request.js
request/tests/test-request.js

A very small, subtle workaround with a lot of code explaining why it's necessary. The test was by far harder to get right than the fix itself, and it required a bit of spec reading and careful coding.
Fixes #2426 
Added a new test, after quite a bit of study on the subject matter. Conveniently, Node also uses V8, so I could easily verify the test there. It shouldn't affect others like Firefox, since they should be "working" already.

Make `m.request` work with `async`/`await` correctly.

---

pathname/assign.js
pathname/tests/index.html
pathname/tests/test-assign.js

Don't call `Object.keys` on falsy argument in `assign` polyfill, to more closely match native `Object.assign` behavior. 
Fixes issue with `m.route` in IE 11, [caused by this line](https://github.com/MithrilJS/mithril.js/blob/next/router/router.js#L63). `history.state` can be null and the `Object.assign` polyfill does not handle it. 
Also see these gitter discussions:
https://gitter.im/mithriljs/mithril.js?at=5d035c64e527d95addcf33d3
https://gitter.im/mithriljs/mithril.js?at=5d03aa40d100e447fc12f6ca
Hand tested.

support falsy arguments in Object.assign polyfill

---

docs/installation.md

I've seen a few recent questions around installing types for v2.rc so I wanted to add a note about installing the `next` branch that I've created on the types dev repo. Going forward this should always align with mithril@next.
I also went ahead and re-arranged the doc a bit. npm installation notes and types installation were at opposite ends of the page. I moved the types ahead of the opus about webpack setup.

Edit types installation docs to be clearer and easier to find

---

docs/change-log.md
docs/parsePathname.md
docs/parseQueryString.md
docs/paths.md
pathname/parse.js
pathname/tests/test-compileTemplate.js
pathname/tests/test-parsePathname.js
querystring/parse.js
querystring/tests/test-parseQueryString.js
request/tests/test-request.js
router/router.js
router/tests/test-defineRoutes.js
router/tests/test-getPath.js
test-utils/tests/test-parseURL.js
test-utils/xhrMock.js

This is multi-part:
- A few parts of the docs were updated to clear up some confusion and bring some clarity.
- Valid URLs must not contain a `#` within its fragment per spec (see #2445). This removes the hash parameter parsing, to bring it in line with spec. (I suspect almost nobody actually uses this.)
- I also removed the extra parameter to `m.parseQueryString`, which existed almost solely to support this.
- I added a bunch of new tests to ensure a few more various edge cases were properly covered, including the report in #2440.
- Prefix handling was corrected, so now, arbitrary URL paths can be used, complete with both path names, query strings, *and* hash strings. For instance, `?#` is now correctly handled as a prefix.
Fixes #2440 by just updating the docs
Fixes #2445 
Also fixes a …

Clarify pathname docs, follow spec with fragments

---

docs/change-log.md
docs/hyperscript.md
docs/keys.md
render/hyperscript.js
render/render.js
render/tests/test-component.js
render/tests/test-fragment.js
render/tests/test-hyperscript.js
render/tests/test-normalize.js
render/tests/test-normalizeChildren.js
render/tests/test-updateNodes.js
render/vnode.js

- Require fragments to either have only keyed children or no keyed children.
- Ban holes from keyed fragments, to reduce complexity in the keyed diff algorithm.
- Normalize booleans, `null`, and `undefined` to be a single hole sentinel `null`, to simplify representation.
- Document a common pattern on how to have a programmatically replaceable node, to resolve some confusion around that.
Closes #2434 
Fixes #2248 
Also resolves a class of paper cuts that have found their way onto Gitter the past several months with v1.
Added a couple tests, updated a bunch, rewrote a few.

Fix keys, normalize holes

---

api/mount.js
api/redraw.js
api/router.js
api/tests/test-redraw.js
api/tests/test-router.js
bundler/bundle.js
bundler/tests/test-bundler.js
docs/change-log.md
docs/route.md
index.js
request/tests/test-request.js
router/router.js
router/tests/test-defineRoutes.js
router/tests/test-getPath.js
router/tests/test-setPath.js
test-utils/domMock.js
test-utils/pushStateMock.js
tests/test-api.js

- Remove appropriate route change subcriptions when a root is removed via `m.mount(root, null)`.
- Don't pollute `onpopstate` and friends - use standard event listeners instead.
- Simplify and streamline subscriptions, in preparation of adding a `remove` parameter to `m.mount`.
- Change the redraw internals to redraw immediately, with ability to cancel via returning a sentinel.
- Change `"bleeding-edge"` for `m.version` in `next` to instead just be the latest `m.version`. (If you're using `next`, you should know what you're in for.)
- Update tests to be aware of these changes. (Some were failing for subtle reasons.)
- Drive-by: remove some uses of `string.charAt(n)` and use `string[n]` instead.
Fixes #2437.
Also, this addresses a couple things that have been in discussion for a while. …

Deduplicate `m.route` and `m.redraw` logic

---

docs/es6.md
docs/hyperscript.md
docs/installation.md
docs/jsx.md
docs/route.md
docs/simple-application.md

- Babel 7 has a whole different module API
- Traceur is basically dead
- JSX != HTML
- Some bits are just obvious from context what they are
- ES6 docs shouldn't be auto-installing JSX support
- Also, I decided it was worth clearing up some misleading docs in surrounding areas.
Fixes #2415 and addresses a few other issues that have come up periodically on Gitter.

Correct a bunch of incorrect/outdated references

---

docs/nav-methods.md

`buildPathname` and `parsePathname` already had doc pages written, however they weren't linked from the API table of contents so I don't think you could get to them. I've added these to the `nav-methods.md` which adds them to the left nav in the API section.
Rebuilt docs, tested on local server

Add build/parsePathname to API TOC

---

.npmignore
bundler/bundle.js
bundler/tests/test-bundler.js
docs/change-log.md
index.js
package.json
scripts/update-version.js

Created an accidental breaking change in #2453, so I'm 90% reverting it. Note that I still want it to be different in the repo, but it'll be `"next"` rather than pulling the actual version from `package.json`. (This will be in a follow-up PR.)
Fixes #2463

Fix `m.version` to not depend on `package.json`

---

docs/keys.md

Fixed an indentation problem in a code block. Also thought some of the notes on mixing keyed/unkeyed vnodes could be clearer so I rearranged a few things and made some edits. Please review my example of using `m.fragment` for an empty vnode, I wasn't sure I understood it properly myself from the existing docs.

Keys docs indent fix, additional edits for clarity

---

README.md
api/router.js
api/tests/test-router.js
api/tests/test-routerGetSet.js
docs/api.md
docs/autoredraw.md
docs/change-log.md
docs/hyperscript.md
docs/index.md
docs/route.md
docs/signatures.md
docs/simple-application.md
examples/threaditjs/app.js
examples/todomvc/todomvc.js
package.json
render/render.js
render/tests/test-render.js
test-utils/domMock.js
tests/test-api.js

- `m.route.prefix(...)` &rarr; `m.route.prefix = ...`
- `oncreate: m.route.link` &rarr; `m(m.route.Link, ...)`
- Add `m.route.SKIP`
Fixes #2387
Fixes #2072
Fixes #1792 
Fixes #2354 (not in the way they wanted, but it at leasts unblocks them)
Fixes quite a few issues reported on Gitter.
For `m.route.Link`:
- More intuitive
- More accessible
- More ergonomic
- It can be disabled
- It can be cancelled
- It can be changed
- Oh, and you can use it isomorphically.
For `m.route.prefix`
- You can *read* it.
- You can write to it, of course.
- It's literally just setting a property.
For `m.route.SKIP`
- You can type-check routes, now.
- You can hide routes and pretend they don't exist.
- You can check existence of something and fall back later.
For the router itself (and the rest of Mithril):
- …

Partially recast the router API to be a lot more intuitive.

---

mithril.js

// The attribute is1 coerced -> // The attribute is coerced
(that extra newline at the end wasn't added by me)

fix small typo in comment

---

stream/stream.js

Changes the signature for stream.map to conform to Fantasy Land spec (one parameter.) All Stream internal/private properties are now marked with an underscore.
The "ignore initial" feature was preserved for internal use in an internally-used `_map` method.
https://github.com/MithrilJS/mithril.js/issues/2479
1. Fantasy Land compliance
2. Clarity for private/public API
Existing test suite ran without errors. (Linux/Ubuntu, Node 10)

Conform stream.map to FL spec and clarify stream internal properties

---

docs/change-log.md
ospec/ospec.js
render/render.js
render/tests/test-onremove.js
render/tests/test-updateNodesFuzzer.js
test-utils/domMock.js

Fixes #1881 
Also fixes a related ospec bug, but I can't seem to find it. (Maybe on Gitter?)
Ran the usual tests. Had to update the mocks so the fuzzer would be seeing an accurate, albeit incomplete, view of the world. (Browsers know how to batch changes in fragments, so the extra removals aren't critical.)

Fix #1881 + related ospec bug

---

docs/change-log.md
querystring/parse.js
querystring/tests/test-parseQueryString.js

Fixes a vulnerability I discovered.
Wrote a few new tests so we don't see it again.

Prevent prototype pollution while parsing query strings

---

docs/change-log.md
ospec/bin/ospec

Fix `ospec --require` with relative paths
The `basedir` option passed to `require.resolve` doesn't seem to be supported for the node implementation of require (https://nodejs.org/api/modules.html#modules_require_resolve_request_options)
Instead, there is a `paths` argument. Replacing `{basedir: cwd}` with `{paths: [cwd]}` fixes this.
This fixes this issue https://github.com/MithrilJS/mithril.js/issues/2489
Locally installed ospec module and tested that `ospec/bin/ospec` works as specified in https://mithril.js.org/testing.html
Ran `npm test` locally
- [ x ] Bug fix (non-breaking change which fixes an issue)
- [ x ] My code follows the code style of this project.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] All new and existing tests passed.
- [ x ] I have updated …

Fix ospec --require with relative paths

---

docs/change-log.md
ospec/change-log.md
render/render.js
render/tests/test-createHTML.js
render/tests/test-updateHTML.js

- Fix double-rendering of trusted content within `contenteditable` elements
- Fix error on `m.trust` updating
Fixes #2502 
Fixes #2498 
Added new tests for each and verified each failed without the appropriate fix.

Unbreak `m.trust`

---

docs/change-log.md
ospec/change-log.md
stream/change-log.md

I'd like to introduce release dates to the change log files.
Release dates are human-friendly and add a bit of historical perspective to change-log files.
@pygy [liked it](https://github.com/MithrilJS/mithril.js/pull/2139/files/87796d612861bb4f770d6631252b71cec7912821#r186195052) when I added dates to the original ospec/change-log.md, but then later they got purged for the sake of cross-changelog consistency, and at my objection @isiahmeadows [suggested](https://github.com/MithrilJS/mithril.js/commit/beb129c5fbf11810a47d3b12d60b55e4b52806bc#r32254656) I make a PR adding dates across the board.
Better late than never, I guess...

docs: Add release dates to all change-log files

---

docs/request.md

As [Can I use](https://caniuse.com/#feat=fetch) shows `fetch()` supported since Safari 10.1 and iOS Safari 10.3.
Removed Safari from the list of browsers that don't support `fetch()`.
This info is outdated.
Other changes to consider (not included in the pull request at the moment):
I don't know: if the first point is still valid or not, as both [Fetch](https://fetch.spec.whatwg.org/) and [XMLHttpRequest](https://xhr.spec.whatwg.org/) specifications were updated this month. Seems both are subject to specification changes.
The second point seems outdated: it's possible to cancel a request using a [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController). [Browser support](https://caniuse.com/#feat=abortcontroller) is almost the same as `fetch()`.
The third point is …

Update fetch() browser support in docs

---

docs/change-log.md
package-lock.json
querystring/parse.js
querystring/tests/test-parseQueryString.js

This PR ports the changes made in https://github.com/MithrilJS/mithril.js/pull/2494 for Mithril 2.x and above to Mithril 1.1.x.
- It fixes a vulnerability in the query string parser that led to direct prototype pollution (https://npmjs.com/advisories/1094).
- It resolves https://github.com/MithrilJS/mithril.js/issues/2519
- It implements the same tests used in #2494 
- In addition, tests were run using `npm run test` and they passed in the following env:
- Mac OS X 10.14.5
- NodeJS v10.15.0

Prevent prototype pollution while parsing query strings on V1

---

api/mount-redraw.js
api/router.js
api/tests/test-mountRedraw.js
api/tests/test-router.js
docs/change-log.md
ospec/ospec.js
ospec/tests/test-ospec.js
pathname/build.js
promise/polyfill.js
render/render.js
render/tests/test-render.js
render/vnode.js
stream/stream.js
test-utils/domMock.js

- I updated error messages to be much more helpful
- For consistency, I normalized error messages to all be sentences and using `'` instead of `` ` `` to denote code and characters.
- I moved the reentrancy check from `m.mount` to `m.render` to be a little more helpful and accurate and updated the router accordingly.
- Technically breaking in the edge case of calling `m.redraw.sync()` inside `oncreate` when rendering from `m.mount` the first time, but the fix here is generally pretty simple and it matches what we've been communicating as reality for `m.mount`.
- I changed the check in `m.route` to align with `m.render`. Minor and you'd be running into errors anyways.
- I corrected `m.route` to propagate the thrown error if it was thrown from the default route's `onmatch`.
- I changed …

Make errors and their messages more accurate and helpful

---

api/router.js
api/tests/test-router.js
docs/change-log.md
docs/route.md

- Add `params:` to `m.route.Link`
- Minor fix to docs to reflect reality with `m.route.Link`'s `disabled:` attribute
- Minor source formatting tweak to signature table for `m.route.Link`.
Fixes #2477 
Added a new test

Add `params:` to `m.route.Link`, fix docs

---

docs/censor.md
docs/framework-comparison.md
docs/hyperscript.md
docs/index.md
docs/keys.md
docs/layout.html
docs/route.md
docs/vnodes.md

- Recast key docs to be much clearer and more accurate, including a few Flems examples to help intuitively explain things
- Also, fix a couple broken hash links I noticed while making this.
- Fixes #2528

Recast key docs to be much clearer and more accurate

---

docs/testing.md

Change the link to point to ospec docs in github.
ospec link went to mochajs 
[issue 2575](https://github.com/MithrilJS/mithril.js/issues/2575)
N/A
N/A
N/A
- [ X ] Documentation change

change link to go to ospec instead of mocha

---

mithril.js
render/render.js

There is a small typo in mithril.js, render/render.js.
Should read `subsequence` rather than `subsequece`.

docs: Fix simple typo, subsequece -> subsequence

---

docs/es6.md
docs/trust.md

While reading through some of the documentation I saw some issues with both the ES6 and `m.trust` pages.  The ES6 page uses the dollar sign wrapped in backticks which causes an issue due to the usage of `String.prototype.replace` in `scripts/generate-docs.js`.  As for `m.trust`, a closing BODY tag was sneaking through to the html.  I just wrapped that code piece in backticks which resolved that.
Saw an issue and easy enough to fix myself and provide an option for resolution.
I ran the tests although it did fail on `test:js` which I'm not sure why.  I didn't touch any of what that would be testing.
```
> mithril@2.0.4 test:js C:\Users\<user>\projects\mithril.js
> node ospec/bin/ospec
the done parser > tolerates comments:
true
should equal
false
at …
```

ES6 and m.trust docs patch

---

docs/change-log.md
render/render.js

Removing an extra isLifecycleMethod in the removeAttr method, it isn't needed since it's already checked on the previous line. It is similarly only checked once in setAttr.
I ran `npm test` as instructed. I also ran `npm run lint` as a sanity check.

Remove extra isLifecycleMethod call from removeAttr

---

examples/dbmonster/ENV.js

One of the example is using the antiquated word "slave" for a database replica. I updated the language and tested the change.
If possible, I'd like to live in a world where we avoid that word.
I've tested the example on my local machine and it seems to work perfectly fine:

replace slave label with replica

---

docs/changelog.md
mount-redraw.js
render.js
request.js
route.js

Recast the global reads to all be guarded with `typeof`, so that if they aren't defined, they're just `null`.
Note that this does *not* involve documentation changes, as that's going to require a lot more effort and is best left as a follow-up. (Our support for this is undocumented anyways, and the relevant docs are for hooking it up with JSDOM. This only really matters in practice if you're using `mithril-node-render`.)
This has been a fairly common gotcha, and I'd like to actually fix it rather than repeatedly tell users how to work around it in about 2-3 different ways (depending on how they test their app). This in effect moves that workaround into core, but without polluting the global scope like #2613.
Closes #2613 
Ran `require("./.")` in the package root from a fresh Node REPL and …

Allow Mithril to be loaded in non-browser environments without modification

---

README.md
ospec/README.md
scripts/bundler-readme.md

"Javascript"/"javascript" → "JavaScript"
Fixes #2398, or at least I can't find any more incorrect capitalizations. Well, there is <https://github.com/MithrilJS/mithril.js/blob/next/render/tests/test-attributes.js#L175>, but that's probably irrelevant (not a documentation file).
Searched all files in VS Code using case-sensitive search terms "javascript" and "Javascript".

Fix inconsistent capitalizations of "JavaScript"

---

request/request.js
request/tests/test-request.js
test-utils/xhrMock.js

Derived from PR #2581. Allows requests to properly reject on event of a timeout. Following up from my previous [comment](https://github.com/MithrilJS/mithril.js/pull/2581#issuecomment-743921642).
* Adjusted timeout handling in `request.js` so that `ontimeout` has a chance to reject
* Adjusted tests for timeouts in `test-request.js`
* Adjusted `xhrMock.js` so the appropriate XHR status and event type are passed to `ontimeout`
* Reverted promisified mocked GET endpoints in `request/tests/test-request.js`, as per @isiahmeadows 's suggestion
Fixes issue #2559
Tested manually via local .html file as well as in flems. Testing via two tests in `test-request.js`
* `npm run test:js` runs and passed after my changes. `npm run test` results in unrelated issues with `stream.min.js` and linting …

Reject request on XHR timeout

---

docs/jsx.md

Naming JSX events according to their documentation produces unexpected results with incorrectly named events when using JSX with Mithril. This PR introduces a short note about this on the JSX resource page.
This change helps new users to correctly name events when using JSX with Mithril. This note should be added as the JSX documentation will instruct to use conventional JSX event naming. The information is relevant for beginners as well as existing users of JSX.
The JSX code example has been tested locally to work as expected with:
mithril 2.0.4
@babel/core 7.12.10
@babel/plugin-transform-react-jsx
webpack 5.11.0

A note on JSX events

---

docs/changelog.md
request/request.js

The bundler mangles identifier-like strings within RegExps, this works around the problem by not using such RegExps.
#2647

[m.request] work around a bundler bug, fix #2647

---

request/request.js

Added guard so that JSON.parse does not fail on IE11 with no content empty string being parsed.
Fixes https://github.com/MithrilJS/mithril.js/issues/2624

Issue 2624 no content 204 parse

---

docs/layout.html
scripts/generate-docs.js

* Add Dropdown that shows links to archived versions of the documentation.
* Modify `generate.js` to checkout /archive from `gh-pages', read folder for previous version names and then reset and delete.
* Add `rimraf` as dev dependency to delete checked-out archive folder. 
* Change layout.html to provide replace target for generated `<select>` tag.
#2334 
Presented working mock-up on Gitter chat for approval.
Ran locally after running `gendocs`

Show previous versions

---

api/router.js
api/tests/test-router.js
docs/changelog.md

fixes #2061
@dead-claudia I just redid your change but slightly different in order to handle a mix of wrong and right encodings properly. Could you take a look please?

Correctly handle invalid escapes in routes based on 0a5ead31c9fbd7b153c521c7f9d3df7bf826ce6c

---

querystring/parse.js
querystring/tests/test-parseQueryString.js

Fix for error thrown when a value contains non-valid / malformed URI Component
Example: test=%c5%a1%e8ZM%80%82H
will throw "URI malformed"
This update will leave the value as-is when an error is thrown

Catch malformed URI Components

---

docs/installation.md

- added link to flems.io as an easier way to just try out the framework.
- 
Documentation has grown a bit stale. Fixes https://github.com/MithrilJS/mithril.js/issues/2599 .

WIP: Update modularisation details in Installation docs

---

docs/route.md

An attempt at better demonstrating `m.route.Link` with less text. Fixes #2767 
Replaces unnecessary HTML-encoded `<code>` tags and character expressions with Markdown counterparts.

Clean up m.route.Link

---

.github/workflows/merge.yml
.github/workflows/pr.yml

Minimizes semver changes on release to the minimum required version bump to satisfy major/minor/patch semver ranges.
Minimizes the semver change so that
- If there are any major changes there will only be a single semver major bump
- If there are no majors, but any minors there will only be a single semver minor bump
- If there are no majors, or minors, there will only be a single patch bump
As an example:
If the prior version was `2.0.8` and the incoming release PR had 37 patch feature branches and 4 minor branches the resulting version would be `2.1.0` as that is the minimum semver version bump necessary to imply a minor update.
If the prior version was `2.0.8` and the incoming release PR had 37 patch feature branches, 4 minors and 2 majors the resulting version would be `3.0.0` as that …

Enable --minimize-semver-change for pr-release

---

.github/workflows/pr.yml

Addresses this issue https://github.com/JAForbes/pr-release/issues/345 (raised by @pygy)
Without specifying target:master the prerelease version calculation would be incorrect as it would never find the open release candidate PR.
https://github.com/JAForbes/pr-release/issues/345
Reproduced and repaired in the debugger locally.

Add missing prerelease branch target.

---

render/render.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

Shave a few bytes by setting `element.style` directly, rather than `element.style.cssText`, since the former is now supported everywhere relevant.

Bypass css text

---

render/hyperscript.js
render/tests/test-hyperscript.js

Whenever there are selector-derived attrs, the attrs object will be regenerated and not shared.
When selector-derived attrs exist, the attrs object is regenerated. However, if the attrs object is empty, the attrs object is not regenerated, and the selector-derived attrs is unintentionally shared.
In this pr, the condition `!isEmpty(attrs)` was removed so that even if the attrs object is empty, the attrs object is regenerated if there are selector-derived attrs.
One tiny bug #2821 has been fixed, and the code outlook is a bit better.
Added test and ran `npm run build`.

hyperscript: handles shared empty attrs, fixes #2821

---

docs/stream.md

Noticed these typos while reading through the page.

Fix typos in `stream()` docs

---

scripts/generate-docs.js

Fixes https://github.com/MithrilJS/mithril.js/issues/2833. I tested the generated documentation on my dev machine successfully.

docs: fix regex for parsing page title

---

docs/nav-methods.md

Not sure how I forgot about this when I added the method.

Add missing `m.censor` to API navigation

---

examples/editor/index.html

Fixes the strange behavior of markdown editor example.
Using newest version of marked.js, fixed strange behavior of markdown editor example.
See #2845 
Manually tested on different macOS browsers.
- ~~New feature (non-breaking change which adds functionality)~~
- ~~Breaking change (fix or feature that would cause existing functionality to change)~~
- ~~My change requires a change to the documentation.~~
- ~~I have updated the documentation accordingly.~~
- ~~I have added tests to cover my changes.~~
- ~~I have updated `docs/changelog.md`~~

fix markdown editor example, bump marked.js version up

---

scripts/generate-docs.js

Fixes #2832 (2 of 2 pull requests).
See my comment at https://github.com/MithrilJS/mithril.js/pull/2835#issuecomment-1535657892.

docs: absolute url in version selector to avoid 404 errors (2 of 2)

---

docs/index.md
docs/simple-application.md

Fixes REM examples in the docs.
The documentation currently has a dead link as REM is no longer hosted on heroku.  I think we should probably rewrite the example to not rely on an external service, but in the meantime I've hosted Leo's REM service on fly.io.
It's not good having broken documentation for the central example of the framework
I updated the flems to use the new service and it worked.  You can [try it out here](https://flems.io/#0=N4IgzgpgNhDGAuEAmIBcICqkBOBZA9ktAHQBWYIANCAGYCWMFqA2qAHYCGAthGpjgSJQyFarHxtEkvgDcO2AARYIigLwLgAHTYLdCqHTDxUC5gF1K2vfvwckAGUPGFNAK5sEdCQAoAlBqtrPWwIeFdsHS5iEIBHVwgjby0dINSeeAALQhNNEABxAFEAFVzLFNTrcKgckAz4eAAHMFQAehauOkzsBgBaEKiaKABPYiIZFo4GuhbXHDBSwIq9AHdOjIBhEKJJOg4oZoV4bHiypYBfX0Wg4kyINm83D3gve5CwVyh4f2Sl62VsYgGIwKdRvD7wUYceAcK7WC5XM5lK6wcIhSQmYCIq5Q …

Temporarily host REM on fly to fix the docs

---

render/render.js
test-utils/domMock.js

Use window and document from render target instead of using globals.
This makes unit and intergration testing much easier.
$window and $doc get set when `render` is called, and are based on the passed `dom`
This decouples mithril from its environment and instead only couples it to DOM.
This allows tests environments to be more easily established, making testing in Node etc easier.
This also allows tests to run in parallel, which, while not needed for mithril it's self, can be useful in larger applications that use mithril.
All the existing tests pass
Happy to check the last points off above if this PR is likely to get merged.

Remove dependance on global window and document

---

scripts/_lint-docs/lint-http-link.js
scripts/_lint-docs/task-queue.js

Missed an edge case in the task queue, and I also wanted to fully dedupe network requests.
Locally it passes.

Fix some outstanding bugs in the docs linter.

---

render/hyperscript.js
render/render.js
render/tests/test-hyperscript.js

Commit f9e5163 made vnode.attrs always non-null, so there is no need for code to make vnode.attrs null or assume vnode.attrs is null.
This pr is a re-opening of #2819.
The following two processes have been removed
- Workaround for vnode of textarea when vnode.attrs is null
- Processing of key removal to set vnode.attrs to null
For the latter, the behavior will change when there is only key in attrs (key is not removed from attrs). Some tests have also been changed to ensure that the changes are appropriate.
There is still a not very useful code that assumes that vnode.attrs will be null. Removing that code will reduce the amount of code and improve the outlook of the process.
Running "npm run test"

Cleaning up code by making vnode.attrs always non-null

---

package-lock.json
package.json

Title's pretty self-explanatory. Also, this isn't really used much in practice.
From a local run:
```
$ npm ci
npm warn deprecated @humanwhocodes/config-array@0.13.0: Use @eslint/config-array instead     
d
npm warn deprecated istanbul@0.4.5: This module is no longer maintained, try this instead:
npm warn deprecated   npm i nyc
npm warn deprecated Visit https://istanbul.js.org/integrations for other alternatives.
added 239 packages, and audited 240 packages in 9s
42 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```
`npm install` after the patch:
```
$ npm i
up to date, audited 212 packages in 2s
42 packages are looking for funding
run `npm fund` for details
found 0 vulnerabilities
```

Drop Istanbul to kill install warnings

---

render/domFor.js

Refactoring of domFor() for the internal bundler.
#2842 appears to be caused by a combination of the mangling of the internal bundler and the parameter destructuring of domFor().
https://github.com/MithrilJS/mithril.js/blob/cfa890f68571df1ab8543097f7fa61c34ee93683/mithril.js#L157
This pr avoids the parameter destructuring to fix the issue.
fix #2842
Observing behavior of reproduction codes on the flems (https://github.com/MithrilJS/mithril.js/issues/2842#issue-1711554047) by replacing with the generated mithril.(min.)js.
Of course, `npm run test` has passed.

m.domFor(): workaround for unintentional mangling. Fix #2842

---

.github/PULL_REQUEST_TEMPLATE.md
package-lock.json
package.json
render/domFor.js

- #2981
- #2979
Refactoring of domFor() for the internal bundler.  https://github.com/MithrilJS/mithril.js/blob/cfa890f68571df1ab8543097f7fa61c34ee93683/mithril.js#L157.
Title's pretty self-explanatory.  Also, this isn't really used much in practice.  From a local run: ```.  $ npm ci.

Release - v2.2.6

---

api/router.js
pathname/build.js
render/hyperscript.js
render/render.js
util/assign.js

Refactor hyperscript.js and render.js. In particular, the replacement of fix #2622 appears to have significantly improved the performance regression.
This change is a refactoring aimed at improving code outlook and performance.
- hyperscript.js now uses Object.assign() to merge attrs. Also, Object.assign() controls the order in which attributes are applied, which addresses issue #2622 alternatively.
- In render.js, performance was improved by eliminating the past #2622 fix. Also, isFileInput has been moved into setAttr() to improve code outlook.
- Polyfill for Object.assign() is removed. The polyfill doesn't support multiple source objects (like in this pr), and almost all browsers now natively support Object.assign().
<details>
<summary>results of `npm run perf` </summary>
before …

[refactor] Refactoring of hyperscript.js and render.js, including performance improvements

---

api/router.js
pathname/build.js
render/hyperscript.js
render/render.js
util/assign.js

- #2983
Refactor hyperscript.js and render.js.  In particular, the replacement of fix #2622 appears to have significantly improved the performance regression.

Release - v2.2.9

---

render/render.js
render/tests/test-createElement.js

This is a refactoring to improve the performance of `updateStyle()`.
In this PR, `style.setProperty()` in `updateStyle()` is used only when there is a dash "-" in the key. This seems to improve performance and reduce code size by eliminating `normalizeKey()` and `toLowerCase()`.
The benchmark "mutate styles/properties" on nodejs show  about an over 50% improvement as follows.
<details>
<summary>results of `npm run perf` </summary>
before (v2.2.9)
> construct large vnode tree x 19,407 ops/sec ±0.66% (124 runs sampled)
> rerender identical vnode x 3,853,625 ops/sec ±0.39% (128 runs sampled)
> rerender same tree x 89,246 ops/sec ±0.15% (126 runs sampled)
> add large nested tree x 7,300 ops/sec ±1.69% (120 runs sampled)
> mutate styles/properties x 76.49 ops/sec ±0.93% (72 runs sampled)
> …

[refactor] Performance improvement of updateStyle()

---

render/render.js
render/tests/test-createElement.js

- #2985
This is a refactoring to improve the performance of `updateStyle()`.

Release - v2.2.10

---

render/render.js
render/tests/test-updateElement.js
test-utils/domMock.js

This PR changes updateStyle() to use setProperty() for dashed-properties.
This PR maybe fixes #2989
Current mithril (v2.2.10) doesn't seem to work well when using something like domMock, which doesn't have enough support for dashed-properties.
It may not be a browser that Mithril officially supports. But the fix is clear and has little or no impact on performance as discussed in #2985.
`npm run test`

updateStyle(): use setProperty() when css vars and dashed-properties, fixes #2989

---

.github/workflows/push-release.yml

Per @dead-claudia's suggestion, pr-release now allows you to invoke a custom command before creating the github release.  If the command fails the process exits with a non zero code and the github release is never created.
This makes it clear that if a github release is created a corresponding npm release with the same tag also exists.
Note I haven't documented this feature as I'm improving documentation and making internal upgrades on another branch.
- Created a test private repo and going through the pr/merge cycle a few times in CI and with the local debugger.
- Deployed pr-release itself using the same process `--prerelease="npm publish"` ([CI](https://github.com/JAForbes/pr-release/actions/runs/11927810216/job/33243786643), [npm](https://www.npmjs.com/package/pr-release/v/0.18.23), …

Use new pr-release prerelease hook (Fixes #2987)

---

render/render.js
render/tests/manual/minlength-input.html
render/tests/manual/minlength-textarea.html

Remove vnode.dom === activeElement(vnode.dom) from setAttribute() to fix validityCheck(), to fix https://github.com/MithrilJS/mithril.js/issues/2256
This is #2257 reopened. (#2257 is for the `next` branch and may not be reopened as is.)
I cherry-picked commit #2257 with additional comments and refactoring.
It appears that #2257 was incorrectly closed due to a typo (with 2557, https://github.com/MithrilJS/mithril.js/pull/2257#issuecomment-2599762079).
#2257 actually fixes #2256.
- `npm run test`
- The following flems were tested using this PR build bundle.
[flems (input)](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10QICsEqdBk2J5YxAARhaAJywUJENAAcArsQDcAHTQ6s+LLVUMAFABNa1VTgb4ARrTMBPBcB0SJ9ajJgZGJgDc0RxgASgk3NA8PaTkJAF4JIJD8CyxtKIl2dySIGAB3QOCzMIicjx9iVRkorB …

Fix form checkValidity(), remove vnode.dom === .activeElement from setAttr() (Continued from #2257)

---

package-lock.json
render/render.js
render/tests/manual/minlength-input.html
render/tests/manual/minlength-textarea.html

- #3002
- #3001
Remove vnode.dom === activeElement(vnode.dom) from setAttribute() to fix validityCheck(), to fix https://github.com/MithrilJS/mithril.js/issues/2256.
Bumps the normal group with 1 update: [glob](https://github.com/isaacs/node-glob).  Updates `glob` from 11.0.0 to 11.0.1.  Commits.  148ef61 11.0.1.

Release - v2.2.13

---

render/render.js
render/tests/test-onbeforeremove.js
render/tests/test-onremove.js

This PR wraps the return value of onbeforeremove in Promise.resolve(). This ensures that thenable objects are also always processed asynchronously.
fix #2592.
The current implementation of mithril calls finally() instead of then() in onbeforeremove process, so that returning a simple thenable object in onbeforeremove will throw an error.
- `npm run test` including additional and modified tests.
- In this PR, I modified the onremove complex test to pass. The test as a whole seemed to assume a synchronous process, including onbeforeremove.

render: wrap stateResult and attrsResult in Promise.resolve(), fix #2592

---

render/domFor.js
render/render.js
render/tests/test-domFor.js

The `generation` of domFor is no longer passed as a parameter.
This allows domFor to work well in onbeforeremove and onremove and reduces the amount of code.
#3005 did not properly take into account that domFor is public API.
This PR fixes these problems (https://github.com/MithrilJS/mithril.js/pull/3005#issuecomment-2628779554):
- The domFor in onremove() does not work well during delayed removal. ([flems](https://flems.io/#0=N4IgtglgJlA2CmIBcBWADAOjQDgDQgDMIEBnZAbVADsBDMRJEDAKzPwGMB7KgF3l+SEArlXY8I3AARR4sGgE8AFGBIBKScAA6VTTwBO8HkL1VJVeAHdJABT2dIJeIoMlOsAG7xJAXgB8GyUceABUIek4hHmd4Vw94XEkVdQBfVW1k7W0EHkl3CBIIACMEH0l9IXhtMAwwCN5FKE52IXpeDELOKHkE4DzLJElFdT9Jcm1JXPyikoAyGcTFTRAoCHclnvGJyW5C+AJOAwNazwHFdypO+GH-LVMtia4qWPgMWE4Ac0WQHb2D+CPOCclmk7vd9npBu4aBDGmBtgREhhYQAxA5nC4yVTqW73e6PZ6vD4NezqAD …

domFor: always get generation from delayedRemoval instead of parameter

---

render/hyperscript.js
render/render.js
render/tests/manual/case-handling.html
render/tests/test-attributes.js
render/tests/test-updateElement.js
render/vnode.js

Fixes a few tiny bugs in attributes and style properties updates, and improves handling of is-elements in updateNode().
- removes `key === "is"` from `setAttr()` to fix 2799 https://github.com/MithrilJS/mithril.js/issues/2799#issuecomment-2464260940
- Also, for code consistency, the `key === "is"` is removed from removeAttr() as well. 
- In addition, is-elements handling in updateNode() has been improved.
- swaps set and removal order in updateAttrs()/updateStyle() to prevent accidental removal for newly setting values
- removes cssText property access as #2811 .
I found a strange behavior in the process of #2985, although it rarely happens (https://github.com/MithrilJS/mithril.js/pull/2985#issuecomment-2459950783). And there seems to be a similar trivial issue in `updateAttrs()` …

Improve handling of is-elements and Fix tiny bugs of setAttr()/updateStyle()

---

render/domFor.js
render/hyperscript.js
render/render.js
render/tests/manual/case-handling.html
render/tests/test-attributes.js
render/tests/test-domFor.js
render/tests/test-onbeforeremove.js
render/tests/test-onremove.js
render/tests/test-updateElement.js
render/vnode.js

- #2988
- #3007
- #3005
Fixes a few tiny bugs in attributes and style properties updates, and improves handling of is-elements in updateNode().
The `generation` of domFor is no longer passed as a parameter.  This allows domFor to work well in onbeforeremove and onremove and reduces the amount of code.
This PR wraps the return value of onbeforeremove in Promise.resolve().  This ensures that thenable objects are also always processed asynchronously.  fix #2592.

Release - v2.2.14

---

performance/test-perf.js

Since Node21, global.navigator has been implemented, and together with browserMock, Benchmark.js incorrectly identifies the execution environment as a browser. It causes error on `npm run perf` in newer nodejs.
If Benchmark.js is loaded before browserMock, the misidentification will be avoided.
I have run `npm run perf` in some environments and found that the newer nodejs versions have an error.
The problem seemed to be caused by benchmark.js misidentifying the execution environment as a browser.
I ran `npm run perf` on node22 and confirmed that no errors occurred.
Of course, node 18 and 20 do not cause errors. Also, benchmark results should not be affected.

test-perf: Load Benckmark.js first in Node.js

---

render/render.js
render/tests/test-attributes.js

This PR limits the evaluation of whether a tag is `option` to only when setting the `selected` attribute.
This PR changes the condition of `vnode.tag === "option" && vnode.dom.parentNode === activeElement(vnode.dom)` within [isFormAttribute()](https://github.com/MithrilJS/mithril.js/blob/v2.2.14/render/render.js#L733) to be like `attr === "selected" && vnode.tag === "option" && vnode.dom.parentNode === activeElement(vnode.dom)`. The only change to the code is addition of a parenthesis.
The condition of the `option` tag is intended to fix #1916 and should be evaluated in conjunction with the `selected` attribute. This commit will improve code readability a bit, reduce the number of times to evaluate tags and also reduce the number of times to set the same attributes in `option` elements …

[refactor] Limit the condition of the option tag to `selected` attribute in isFormAttribute()

---

performance/test-perf.js
render/render.js
render/tests/test-attributes.js

- #3011
- #3008
This PR limits the evaluation of whether a tag is `option` to only when setting the `selected` attribute.
Since Node21, global.navigator has been implemented, and together with browserMock, Benchmark.js incorrectly identifies the execution environment as a browser.

Release - v2.2.15

---

render/render.js
render/tests/.eslintrc.js
render/tests/test-event.js

This PR allows redraw on completion of the async event handler.
This PR makes redraws when Promises returned by event handlers are completed. This allows for async event handlers to be redrawn on completion of the function as well as synchronous event handlers.
This is like re-opening the #2862  that was accidentally closed.
Unlike  #2862 , this PR ~uses `Promise.finally` to handle the return value and also~ adds the condition `event.redraw === false`. Therefore, I did not cherry-pick #2862 .
I added the tests and confirmed that `npm run test` passes.
I also added eslintrc because the new test code includes the async functions.

feat: Make redraws when Promises returned by event handlers are completed

---

render/render.js
render/tests/test-event.js

This PR allows asynchronous redraw processing even if the first redraw is skipped by setting `event.redraw=false` before await in the async function.
Also, this PR avoids redraw after the dom or component is removed.
This PR is intended to address the following cases of [zulip](https://mithril.zulipchat.com/#narrow/channel/324076-general/topic/Should.20async.20event.20handlers.20be.20a.20semver.20major.20change.3F/with/516572123)
> If it was set to `false` before the first await and then `true` after it, the first redraw should be skipped, but the second one shouldn't.
In #3020 , I didn't consider the case where `event.redraw` would later be `true`.
`npm run test` with additional test

Allow additional async redraw even if the first redraw is skipped

---

.github/workflows/notify-release.yml
.github/workflows/publish-prerelease.yml
.github/workflows/test.yml
README.md
package-lock.json
render/render.js
render/tests/.eslintrc.js
render/tests/test-event.js

- #3021
- #3020
- #3019
- #3015
This PR allows redraw on completion of the async event handler.  This PR makes redraws when Promises returned by event handlers are completed.
This PR allows asynchronous redraw processing even if the first redraw is skipped by setting `event.redraw=false` before await in the async function.
Bumps the normal group with 1 update: [glob](https://github.com/isaacs/node-glob).  Updates `glob` from 11.0.1 to 11.0.2.  Commits.  fd61f24 11.0.2.
The URL for the Shields.io badge for build status has been corrected.

Release - v2.3.0

---

api/tests/test-router.js
pathname/compileTemplate.js

- #3025
Regexp has been updated to set trailing slash as optional in route matching.  link to issue 3024.  New test has been added.

Release - v2.3.1

---

api/router.js

This PR refactors the router code to fix two issues (#2505 and #2778).
This will make the router code a little easier to read and reduce the bundle size (8.97kB(gzipped)).
I wanted to close two router-related issues (#2505 and #2778) that had been left unresolved for a long time.
Although these issues do not seem to cause any big problems even if they are not fixed, the fixed bundle size seemed to be smaller than I had expected.
`npm run test`

Refactor router, fixes #2505 and #2778

---

api/router.js
api/tests/test-router.js

This PR delays the initial mounting of the router component until after the route has been resolved.
Since the component that displays nothing is no longer mounted first, the following improvements are made.
- Errors are no longer caught by `m.mount` when the actual component is first rendered, and #2621 is fixed.
- Since the root DOM is not manipulated until the actual mounting, it makes easy to display something like "loading..." when using `onmatch` (cf. #2490).
In addition, cleanup code has been added to RouterRoot's `onremove` to pass the test.
fixes #2621, and enables "loading..." like #2490
`npm run test` with new tests
I have also confirmed that replacing the bundle improved the behavior of the following flems.
- [flems #2621](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAX …

router: delay mounting RouterRoot until the first route is resolved (fixes #2621)

---

api/router.js
api/tests/test-router.js
package-lock.json

- #3030
- #3029
This PR delays the initial mounting of the router component until after the route has been resolved.
Bumps the normal group with 1 update: [glob](https://github.com/isaacs/node-glob).  Updates `glob` from 11.0.2 to 11.0.3.  Commits.  af2e7ce 11.0.3.

Release - v2.3.3

---

.github/workflows/pr-create-release.yml
render/tests/test-normalizeChildren.js
render/vnode.js
scripts/_bundler-impl.js
scripts/tests/test-bundler.js

- #3037
- #3032
The previous condition was basically "if this is non-nullish or a boolean".  That "or a boolean" is very obviously redundant.
This PR removes unnecessary suffixes from comments in the bundle file.  It also fixes the strange double suffix (`mountRedraw00`).

Release - v2.3.4

---

render/fragment.js
render/hyperscript.js
render/tests/test-fragment.js
render/tests/test-hyperscript.js

In #3041, it seemed that the case of non-element vnodes was not fully considered in terms of not breaking existing behavior.
#3041 moved the process of setting attrs to non-null outside of hyperscriptVnode. However, it did not fully address cases involving non-element vnodes. This PR adds handling for non-element vnodes.
Fix unintended breaking change and maybe fix https://github.com/MithrilJS/mithril.js/pull/3041#issuecomment-3227110871
`npm run test`, including additional tests

Make the attrs of non-element vnodes always non-null.

---

render/fragment.js
render/hyperscript.js
render/tests/test-fragment.js
render/tests/test-hyperscript.js

- #3042
In #3041, it seemed that the case of non-element vnodes was not fully considered in terms of not breaking existing behavior.

Release - v2.3.6
