Gruntfile.js
docs/layout/api.html
docs/layout/guide.html
docs/layout/index.html

I got frustrated having multiple tabs open for reference with just the title "Mithril" showing

documentation pages should have titles

---

mithril.js

fix issue #424

---

mithril.js

handle mixed type children correctly - fixes #443

---

mithril.js

always select exact route if it exists

---

mithril.d.ts

Currently mithril.d.ts has a lot of usages of the _any_ type. Often in TypeScript it's desirable to have stricter definitions, to get the full benefit of the compiler. 
_any_ pretty much circumvents the compiler, like _dynamic_ in C#. So it will compile, but won't necessarily be correct and may throw errors at runtime. For this PR I've systematically eliminated _any_ from the .d.ts, which will hopefully make it easier to write correct TypeScript programs. In the process I found and fixed a few other minor differences between the defs and what Mithril actually does (and learned a ton about dynamic programming, haha).
To test that these stricter definitions are correct, I ported the unit tests to TS with minimal changes beyond adding type annotations. These compile (including with the …

Stricter TypeScript definitions

---

docs/layout/style.css

Should make the documentation pages feel less compressed.

Set base line-height to a decent default.

---

docs/components.md

Still needs styling for the drop area to occupy any space though. Worth putting in as inline styles?

Fixed uploader demo code

---

docs/components.md

fixes for https://github.com/lhorie/mithril.js/commit/0ea9fac07e466f5c0bcc48412412b7be3bf658b7

fix drag-n-drop uploader docs

---

docs/getting-started.md

This example is a little simplier and probably faster because it:
* does not create a new closure
* does not call a closure
* does not create a new variable (vm)
* does not search for that variable in two scopes every time it needs to be used

A simplier example with less code

---

docs/getting-started.md

added a link for the example app in jsfiddle for people.

---

mithril.js

https://github.com/lhorie/mithril.js/issues/560#issuecomment-93876904

Prevent scroll on redraw called inside onunload if previous onunload calls preventDefault

---

tests/mithril-tests.js

This is a working test case for #571 - but it's failing when run after the test immediately before it. If you comment that one out, it passes. Any idea what's going on?

Add test case for #571

---

docs/mithril.component.md

These changes make the the text clearer to me. I didn't aim to change the voice of the text, but I tried to clear out some verbosity and improve consistency. I did my best not to interfere with the logic of the prose.
This document seems written to stand on its own, so I recommend the following changes:
- a general explanation of the args param as in `controller: function(args) {` and `view: function(ctrl, args) { ...` (when first used, well before the signature)
- a specific explanation of {data: args} in m.request() (mithril.request.md could use the same treatment)
- an explanation of the extras param as in `controller: function(args, extras) {` and `view: function(ctrl, args, extras) { ...`
- the term *rollback* should be explained or replaced
- caveat #3/#4: Should *root element* be …

Docs: mithril.component.m - Recommended changes

---

docs/mithril.component.md

The formula was right, just some variable typos.

Fix conversion in component stateless example

---

mithril.js

Remove unused variables

---

docs/mithril.component.md

Fixes https://github.com/lhorie/mithril.js/issues/652

DOCS: missing comma in example

---

docs/getting-started.md

Addresses https://github.com/lhorie/mithril.js/issues/624

Change JSFiddle example to use Mithril 0.2.0

---

docs/mithril.component.md
docs/mithril.redraw.md

Do you need me to create an issue before little things like this?

Fixed typos in doc links

---

mithril.js

Hello mithril community. I was looking at the code in file mithril.js and discovered there are bunch of missing semicolons (eslint used here). I thought it could help you to add them back.

fixed missing semicolons

---

mithril.js

When key=0 the if statement doesn't do what is intended.

mithril.js: fix if clause that expects truthy value. issue: #689

---

docs/components.md

@ArthurClemens pointed out in [this gitter comment](https://gitter.im/lhorie/mithril.js?at=55664ba1d21e5ed02ff06e54)
that the [Classic MVC example](https://lhorie.github.io/mithril/components.html#classic-mvc) is broken.
I wanted to show a working jsfiddle with these changes applied, but I couldn't figure out how to get a POST request working. I do, however, have a jsbin that is working, although there are significant changes in the code to allow for GET and POST.
http://jsbin.com/cokesu/2/edit?js,output
I did not check if these changes are required in other examples on the page.
A redraw is called for every character entered in the jsbin but AFAICT, not in this PR. I don't know why. It's as though `oninput` is really `onchange`. It's possible to limit the redraw to once when the "save" …

Update components.md -- "Classic MVC" example broken

---

docs/components.md

Oops!
Thanks to @gaydenko and @impinball

components.md - eliminate global variable introduced in previous commit

---

docs/web-services.md

I think I got a grasp of what the document intended to state but if I'm wrong let me know and I'll fix it.

rephrase sentence on web services doc

---

mithril.js

Fixes #718. Prefer this to #719, as it repairs the lost semantics that were there before.

Forgot to assign the default argument

---

mithril.js
tests/mithril-tests.js

from my comment in the gitter discussion.

added version function to mithril and test for version function

---

mithril.js

Addresses #638, however if this functionality was intentional then it should be ignored.

Stop subsequent redraws appending arguments to parameterized components

---

mithril.js

Line: 595 function() {} -> noop
Remove blank at the end of the line

function() {} -> noop

---

tests/mithril-tests.js

This is the test case for #660

Added tests for parsing empty string, and building from empty object.

---

mithril.js
tests/mithril-tests.js

Add `finally` to promise-like object.

---

mithril.js

Signed-off-by: islahul <islahulzunjani@gmail.com>

style fixes spaces and indentation

---

mithril.closure-compiler-externs.js

Just a small update to Mithril's externs file for the Google Closure compiler.

Update externs for Google Closure compiler

---

README.md
dragdrop.html
guide.html
mvc.html

README still references m.module, since that changes to m.mount in 0.2.0 we should update the docs as well.
This PR fixes the README sample code.

Change m.module to m.mount in documentation

---

README.md

This would now be consistent with the size of mithril.min.js.gzip

Update README gzip size statement

---

.travis.yml

@see http://docs.travis-ci.com/user/migrating-from-legacy/?utm_source=legacy-notice&utm_medium=banner&utm_campaign=legacy-upgrade

Use modern TravisCI platform

---

docs/mithril.component.md

see Issue: https://github.com/lhorie/mithril.js/issues/839

FIX: document error on master branch according to #839

---

mvc.html

Is this mvc.html still maintenanced? I found old api call and fixed it.

Change m.mount to m.component in sample html

---

Gruntfile.js
package.json

As per https://docs.npmjs.com/files/package.json#name as mentioned by @Pumpuli
in #845.
My bad.

Revert to lowercase NPM package name

---

mithril.js

Overriding extract option in m.request

---

docs/layout/tools/template-converter.js
mithril.js
test-deps/mock.js

travis was erroring because of eslint troubles.
I've fixed the linting so travis should run fine now

fix linting errors

---

tests/unloadingTest.html

The test currently fails. See Issue #694 for details.

Add an interactive test called unloadingTest.html

---

mithril.js

Fix issue with a placeholder

---

mithril.js

Fixed Issue -  mithril not aborting the diff algorithm for the {subtree:retain}
directives.

Subtree Directives Not Working - Issue Fix

---

mithril.js

https://github.com/lhorie/mithril.js/issues/924

Fixed setAttributes for custom components (like Polymer uses) with readonly properties

---

archive/v0.2.2-rc.1/tools/template-converter.js

Added undefined check at line 76 to prevent an uncaught type error which was occurring when the class attribute was encountered.

fix for issue #915

---

mithril.js

Cleaned up comment on line 557

---

docs/mithril.component.md

Revert "Fix docs error"

---

.eslintignore

I'm working on that patch separately, but this is a short term build fix.

Don't lint old tests (yet)

---

docs/mithril.component.md

Typo in docs/m.component.md #938

Issue #938 Fixing typo

---

docs/mithril.component.md

Fixing typo in mithril.component.md file

---

docs/tools.md

Switching to @arthurclemens modified template converter

Amending template converter

---

mithril.js

Trying to make a few small things faster, shorter and more readable.
I split those up into discreet commits to make it easier to cherry-pick/reject each one.

Minor tweaks

---

mithril.js

http://jsperf.com/arguments-slice-vs-for-loop-copy
I don't have any actual perf numbers for mithril, can put them together if you'd like.
Also didn't regenerate the `.min.js` file, but can do that trivially as well if it'd help!

Use for-loop to map arguments instead of slice

---

mithril.d.ts

I broke previous commit after uncorrect merging from next. https://github.com/lhorie/mithril.js/pull/984

In continue of #984

---

mithril.js

Serialize arguments correctly in m.component

---

README.md

Since we covered it in gitter but it was missing from the readme. These are pretty rough and potentially incorrect but it's better than nothing!

Added lifecycle method descriptions

---

examples/dbmonster/mithril-0.2.x/app.js
examples/dbmonster/mithril-0.2.x/index.html
examples/dbmonster/mithril-0.2.x/mithril-0.2.4.js

Seems useful, if only for science!
Rewrite running 3x faster than this verison on my local FF instance. :clap: :+1: :smiley:

Add mithril@0.2.x version for comparison

---

limiter.js
mithril.js
mount.js
router.js
test-redraw.html

Tries very hard to render every 16ms, but not any faster.
Test file needs a better home, just left it in the root for now.

[rewrite] Rate limit re-renders w/ m.mount/m.route

---

.gitignore
package.json

Using istanbul, and also adding a .gitignore so I can be lazier about things when committing.

Add cover command

---

render/hyperscript.js

Uglify caught this when I was testing to see what the updated min+gzip size was.

[rewrite] Remove unused var

---

README.md

Sad to say but `rewrite` has packed on 1.1kb since this was last updated.
It's all my fault :cry:

[rewrite] Update size

---

examples/dbmonster/mithril-bundle/app.js
examples/dbmonster/mithril-bundle/index.html

Might as well, especially since it looks more like what existing mithril users are used to.

[rewrite] Add mithril bundle version of dbmonster

---

.eslintrc.js
.gitignore
api/throttle.js
module/module.js
request/request.js

Some via config, a few via code edits.
The `module` one is a bit weird, but I get why it's done that way so just worked around it in the ESLint config.

Quiet some ESLint errors

---

docs/components.md

Typo in component.md

---

docs/v1.x-migration.md

I'm sure there's other pieces I'm forgetting, but this is at least enough to start talking about formatting and how we want to handle comparisons between `v0.2.x` and `v1.x`.

Starting on a migration guide

---

docs/v1.x-migration.md

Not merging this one immediately because I'm worried there are subtleties that I'm missing and it's late.

Component options section

---

router/router.js
router/tests/test-defineRoutes.js
router/tests/test-getPath.js
router/tests/test-setPath.js

This may solve #585 
Edit: or more precisely, @zah's issue when using `pathname` routing.

Support non-root base path

---

docs/v1.x-migration.md

- Getting/setting current route
- Reading route params
- Haven't tackled the route prefixing stuff yet, got my hands full today unfortunately.
As requested by @s3ththompson here: https://github.com/lhorie/mithril.js/issues/1044#issuecomment-223610519

Add more docs around `m.route`

---

ospec/ospec.js

exit on error to be able to rerun the process

ospec exit on error

---

examples/threaditjs/app.js

I guess the leftovers of a previous version...

Remove the injection of `Stream` into `requestService`

---

docs/prop.md

Seems like some copy paste slipped through ;)

Correct descriptions for map in table

---

mithril.js
test/mithril.route.js

This PR contains the fix for issue #1124 provided by darda in #1125 and the requested tests for the fix.

Tests for issue #1124/#1125

---

render/tests/test-onremove.js

Fix the onremove tests

---

mithril.js

I haven't updated the typescript definitions because I've never used typescript...

Resore m.factory

---

render/render.js
render/tests/test-onbeforeremove.js

[rewrite] Pass `vnode.state` as context to `onbeforeremove`.

---

render/tests/test-onbeforeremove.js

Remove a few crumbs I left behind

---

mithril.js

fix potential overwriting of onunload.$old

---

util/tests/test-stream.js

Making Travis green again until it gets fixed.

Comment broken test temporarily

---

docs/request.md
docs/v1.x-migration.md
request/request.js
request/tests/test-xhr.js

Related discussion in https://github.com/lhorie/mithril.js/issues/1212

Rewrite: ignore m.request deserialize option if extract is passed

---

.travis.yml

By adding the commit that triggered it for easier referencing.

Improve travis commit message slightly

---

render/render.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

Builds on #1219, fix the mocks.

Overwrite an element's style using cssText (with tests fixed).

---

render/tests/test-render.js

Clean up test for #1222 a bit

---

mithril.js

IE8 compatibility fixes

---

mithril.js
tets.html

Sorry for breaking tests. I think better solution would be ignore that exception for IE8, especially in case every other browser works well.

Fix broken tests

---

render/tests/test-hyperscript.js

Was looking at coverage for something else and noticed a few cases getting missed. Seemed easy to fix so here we are.

Improve hyperscript test coverage

---

api/mount.js

[Well...](https://github.com/lhorie/mithril.js/blob/a3c273f802e9cb386ca170a3276df93981a402a9/api/autoredraw.js#L14)

Move otherwise redundant unsubscription

---

ospec/package.json

Add package.json to ospec so it can be published

---

ospec/package.json
package.json

`ospec`
- add `bin`
- add `repository`
`mithril`
- add `repository`
- remove `bin`

Update package metadata

---

api/router.js
api/tests/test-router.js
docs/route.md
route.js

This is a layered PR to fix #1180, #1268, #1275, #1286, #1276 and part of #1277.
The fix for the first four amount to a complete rewrite of `api/router`, and the fix for the other two depend on the first fix, hence the grouping.
I couldn't disentangle this more without getting headaches.
A second PR that adresses #1269 will follow.
Edit: Note that this adds two seconds of test run time... I'll address that in the followup PR that affects the timing of the core router.

Mount based router

---

api/tests/test-mount.js
api/tests/test-router.js
render/render.js
render/tests/test-render.js

Validate the DOM node passed to `render`

---

docs/integration.md

Hey! per #954 I went ahead and modified the docs to have a cleaner, less headache inducing example for integrating select2. 
I tried to stray from talking too much about `m.startComputation` and `m.endComputation` like they were what you needed to do. I don't know who authored this section prior, but I also feel like redrawing in the config isn't the devil? 
let me know if there's language/etc that should be changed!

update Select2 integration example and explanation

---

examples/dbmonster/react/index.html

fb.me is blocked on certain LAN's breaking the example and isn't the recommended link in https://facebook.github.io/react/downloads.html

Update react example

---

api/tests/test-router.js

I've tested in my single-core CentOS machine, it don't pass the test due to timeout is restricted.

[rewrite] Double test timeout for test pass in old machine

---

README.md

Add link to wiki in readme

---

docs/withAttr.md

replace `value` with `attrName` for the parameter representing the property/attribute name

update m.withAttr signature

---

examples/dbmonster/vue/app.js
examples/dbmonster/vue/index.html

For comparison with the others.

[rewrite] Add vue 2 dbmonster example

---

request/request.js
request/tests/test-request.js

I think this covers the nice convenience overload of being able to pass a single string or string followed by options, with GET method as default.

Fetch-style signature overload

---

examples/todomvc/todomvc.js

Observed behavior: The todomvc example did not respond to clicking on the links in the footer for All, Active, and Completed.
Expected behavior:  The todomvc example should respond to clicking on the links in the footer for All, Active, and Completed.
This PR fixes todomvc to work as expected.

Fix todomvc to reflect All/Active/Completed choice

---

render/render.js

A simple raw js (no mithril) showcase of the chrome issue can be seen here:
https://jsfiddle.net/porsager/1r9qLqm3/
I've also posted a chromium bug here:
https://bugs.chromium.org/p/chromium/issues/detail?id=667148

Don't set same value of options in focused select - fixes #1413

---

render/hyperscript.js
render/tests/test-hyperscript.js

Allow verbose class attribute declaration

---

api/router.js
api/tests/test-router.js

This fixes a couple of bugs in the new router code (I had left a few holes in the test suite).

[rewrite: api/router] Misc router fixes

---

api/router.js

A few tweaks. 
The first patch adds three bytes mingzipped, but avoids mutating user-provided objects.
The second one shaves about 30.

[rewrite] router cleanup

---

ospec/ospec.js

Extend final report to log the number of failing assertions

Ospec: report failure count

---

api/router.js

AFAICT this one should not enable race conditions.

[api/router] simplify the route finalization logic

---

render/render.js
render/tests/test-attributes.js

Ensure custom element attributes are always updated via setAttribute

---

promise/promise.js

I wasn't sure what to do in the `else`.

Fix #1489: PromisePolyfill always overwrites `window.Promise`

---

stream/stream.js

Make it work in a browser

---

docs/installation.md

Fewer steps to get a complete app running in the browser with live reload.

Recommend 'budo' for the quickest start ever

---

ospec/ospec.js
ospec/tests/test-ospec.js

Fix incoming once Travis is done.
Edit: there. Now it also supports holes in arrays...
But wait, there's more (I just noticed a similar hole in the code that deals with objects)
Edit 2: Done :-)

[ospec] deepEquals corner cases with undefined values

---

docs/keys.md

Rather than manually creating a vnode-like object.
(I think this is in line with the intent of fragments? Apologies (and feel free to ignore me) if this is wrong :-) )

Recommend usage of fragments

---

ospec/ospec.js

[ospec] fix nextTickish()

---

querystring/build.js
request/request.js
request/tests/test-request.js

remove mutating of interpolated data

---

render/tests/test-render.js

Edit: I'll put the potentially contentious parts in another PR.

Re-enable the test suite

---

docs/simple-application.md

A few people (self included) have had trouble trying to use http rather than https.
On the edit form, the browser will attempt to submit without the event.preventDefault. (Using the form's onsubmit would also allow you to add HTML5 form validation...)

Minor fixes to get the tutorial working

---

mithril.d.ts

This PR adds typescript definitions for class and factory component types. Also adds JSDoc comments for improved in-editor help.

Add class and factory component type definitions.

---

api/tests/index.html
api/tests/test-mount.js
api/tests/test-router.js
render/render.js
render/tests/index.html
render/tests/test-component.js
render/tests/test-onbeforeremove.js
render/tests/test-onbeforeupdate.js
render/tests/test-onremove.js
render/tests/test-render.js
render/tests/test-updateNodes.js
test-utils/components.js
test-utils/tests/index.html
test-utils/tests/test-components.js
tests/test-api.js

This builds on top of #1643 and fixes #1638 and #1641 
The tests for #1641 are fairly minimal... I may add a `test-recycling.js` file at some point (to get a better hang of how it works and systematically centralize knowledge about how the recycling pool works).
Edit: Over #1643:
- [this reworks the tests a bit more substantially](https://github.com/lhorie/mithril.js/pull/1652/commits/1dd5fe310127557ad19c679f9115a05981e0518e) and 
- [these are the #1638 and #1641 -related changes](https://github.com/lhorie/mithril.js/pull/1652/files/1dd5fe310127557ad19c679f9115a05981e0518e..ca5c68ae8a109306bc6511b52b4af8d129255e9f)
Edit2: I refactored the final commit to save a few bytes and branches.

Fix state initialization

---

docs/keys.md

Hint to avoid problems such as those found here [February 23, 2017 6:28 PM](https://gitter.im/lhorie/mithril.js?at=58af29c47ceae5376a2d470e)

Warn about data models w key props passed as attrs

---

stream/stream.js

...when imported into the browser via <script> tags.

Put Stream in IIFE so variables aren't global

---

.eslintrc.js
api/redraw.js
api/tests/test-router.js
bundler/tests/test-bundler.js
package.json
promise/tests/test-promise.js
stream/tests/test-stream.js
test-utils/components.js
test-utils/tests/test-components.js

* Fix 2 existing lint issues
* Add `indent` rule with `tabs` options (as per `.editorconfig`)
* Add fix script to quickly fix issue
* I used it in this PR to fix indent tab issues

Chore: Fix lint issues and add indent with tabs

---

stream/stream.js

Changing m.prop.combine and m.prop.merge to stream.combine and stream.merge

Replace m.prop reference in error message

---

docs/simple-application.md

I went through the tutorial, which is great btw. 
However:
`button[type=button]` was not working for me.
`button[type=submit]` did.

button[type=button] => button[type=submit]

---

docs/framework-comparison.md

RE: https://gitter.im/lhorie/mithril.js?at=58db36d2ad849bcf422cb1e7
CC @tivac @calainos

Acknowledge multiple component creation strategies

---

docs/generate.js
docs/index.md
docs/layout.html
package.json

To allow potential users to futz around with `m` in the dev console, no setup required.

Load mithril on mithril.js.org

---

docs/code-of-conduct.md
docs/nav-guides.md

I think it's important, even if we haven't had any issues yet it's better to be prepared with expectations made clear.
@lhorie this one 100% needs your sign-off

Add code of conduct

---

render/tests/test-input.js

Added a test case for https://github.com/lhorie/mithril.js/issues/1814

Add test for select option with empty string value

---

docs/jsx.md

Add missing "!" to result of interpolation for `{greeting + "!"}` expression

docs(jsx.md): add missing "!"

---

examples/todomvc/todomvc.js

Quick fix to prevent empty todos created as in the original app.

Todomvc example: Prevent create empty item

---

render/render.js
render/tests/test-attributes.js
test-utils/domMock.js
test-utils/tests/test-domMock.js

Don't update textarea.value if the `DOM.value === vdom.value !== old.value`, Fix #1870

---

render/render.js
render/tests/test-render.js

Take the namespace of the root node into account, fix other ns oversight #1872

---

.github/CODEOWNERS
.github/ISSUE_TEMPLATE.md
.github/PULL_REQUEST_TEMPLATE.md

What is a code owners file? https://github.com/blog/2392-introducing-code-owners
Issue/PR template docs: https://github.com/blog/2111-issue-and-pull-request-templates
These are really nice in other projects I've sent Issues & PRs to, so I think Mithril should have 'em too.
Happy to bikeshed formatting/wording for a bit if folks care to.

Add Issue/PR templates & a basic owners file

---

.github/PULL_REQUEST_TEMPLATE.md

Wanted to call it out more clearly in the PR template since danger will be checking for it soon.

Add changelog checkbox to PR template

---

docs/change-log.md

Move the #1921/#1922 line into the v1.1.4 change set

---

docs/change-log.md
render/render.js

Same as #1943 .
Creating new PR to merge fix into v1.1.4.

Fixing IE bug causing active element to be null causing render function to throw error

---

docs/components.md

Actually, should the MR be made against master or next? I'm not sure, also I think contribution guide doesn't mention it. :)

Fix typo in code snippet

---

docs/components.md

docs: reorder lifecycle methods to match actual event order

---

docs/change-log.md
request/request.js
test-utils/tests/test-xhrMock.js
test-utils/xhrMock.js

See #1919
- [v] Bug fix (non-breaking change which fixes an issue)
- [v] My code follows the code style of this project.
- [v] I have read the **CONTRIBUTING** document.
- [v] I have added tests to cover my changes.
- [v] All new and existing tests passed.
- [v] I have updated `docs/change-log.md`

re fix issue #1919 for the v1 branch

---

docs/code-of-conduct.md

Fix mailto link

---

docs/change-log.md

Sync change log with v1.1.6

---

docs/style.css

Fixed missing background for body, which causes browser default to apply, resulting in unreadable content
When default browser background is dark the pages are unreadable
Previewed the page

Fixed background issue

---

test-utils/domMock.js
test-utils/tests/test-domMock.js

As discussed in Gitter this implements adding capture phase events via hyperscript.
I've also added event propagation, eventPhase and currentTarget support in the mocks (with tests).
@tivac seems to be against the first change, so I'm waiting for more feedback before I add framework tests (if at all).
```JS
m.render(root, m('div', 
{
// calling e.stopPropagation here would stop further handlers from firing
onclick_capture(e) {console.log(1)}, 
onclick() {console.log(3)}
},
m('button', {onclick(){ console.log(2) }, "clicky"})
))
// click the button, logs: 1  2  3
```
This can be useful in event delegation scenarios where `e.target` points to the event that triggered the event while `e.currentTarget` points to the element on which the event was defined.
@spacejack wondered if we could …

Mocks: Add event propagation (and pave the way for more event options)

---

docs/integrating-libs.md

Doc / example for lib integration.

Integrating libs

---

api/tests/index.html
stream/tests/index.html
test-utils/tests/index.html
tests/index.html

I noticed these issues by testing on Windows 7 x64 in Chrome.
Fixes a few errors and notices in tests by testing with index.html files.
Locally.
Tests.

Correct test scripts

---

docs/index.md

Fixed a typo.
Fixed a typo.
N/A

fix typo (replace "we" with "we're")

---

docs/installation.md
docs/layout.html

TypeScript and GitHub are camel cased, and this fixes two instances where it's not in the documentation.
This also adds a note about adding the `bin/app.js` file in the Getting Started section. Running these steps can throw an error that the file doesn't exist.
Casing changes are just for proper naming.
The note about `bin/app.js` solves an issue that beginners with MithrilJS might see and not know how to solve right away.
I ran it in my browser.
Might be too minor to be considered a bug fix, but that's the closest thing to what this is.
I didn't add anything to the Changelog because this is very minor, but happy to add that to the PR if needed.

Minor casing changes, note about missing file error

---

render/render.js

Document an otherwise obscure implementation detail.

Document the reason for the possibleParents map

---

docs/change-log.md
docs/render.md

Added missing parenthese to reduce confusiion.
Added single `)` in docs
Saw problem, submitted fix
Preview [### How it works](https://github.com/mikeyb/mithril.js/blob/858dce214e9f22d3868bf240bf829ca8a40133da/docs/render.md#how-it-works)

Mikeyb patch 1

---

docs/jsx.md

docs: Fix webpack example

---

docs/installation.md
docs/integrating-libs.md
docs/learning-mithril.md
docs/nav-guides.md
docs/support.md

docs: Fix some site weirdness

---

docs/animation.md

Tiny text corrections in animation.md

---

ospec/change-log.md
ospec/package.json

Here we go (publishing to NPM will follow soon)!

[ospec] v2.0.0

---

docs/change-log.md
docs/stream.md
stream/change-log.md
stream/stream.js
stream/tests/test-stream.js

stream: Removed `valueOf` & `toString` methods (fixes #2150)

---

ospec/change-log.md
ospec/package.json

ospec v2.1.0

---

ospec/README.md
ospec/change-log.md
ospec/ospec.js
ospec/tests/test-ospec.js

This adresses the issues raised in #2154, #2159 (some of them), #2162 and #2166. (WIP, adding docs and the change log)
@barneycarroll I'll leave you the pleasure to remove the `done()` check.

[ospec] Async fixes... This devolved badly... welcome ospec@3.0.0 :-)

---

ospec/change-log.md
ospec/package.json

[ospec] v3.0.1

---

docs/examples.md

Added a link to Stephen Hoyers How To Mithril page to allow community members to better document examples
see above
no failing tests

adding stephen hoyers how-to-mithril to examples page

---

bundler/bundle.js
bundler/cli.js

Setting the errorCode within bundle.js does not change the exit code
when called with cli.js.  This moves the outer `try...catch` from
bundle.js to the `bundle` call in cli.js, so it can set the exit code.
fixes #2240 
I tested this manually by changing an import path in `index.js` and running the bundler manually and with npm:
```
node bundler/cli.js browser.js -output mithril.js; echo $status
File does not exist: /Users/jg/code/personal/mithril.js/requestx.js
1
npm run build-browser
...
File does not exist: /Users/jg/code/personal/mithril.js/requestx.js
...
npm ERR! errno 1
```

Exit process with error on bundler errors (#2240)

---

render/vnode.js

I changed Vnode.normalizeChildren to anonymous function
Since Vnode.normalizeChildren was declared as a normal function, I changed to an anonymous function. This is not a feature addition but a suggestion for code consistency.

refactor: Vnode.normalizeChildren to anonymous function

---

bundler/minify.js
package-lock.json
package.json

1. It's actually supported
2. It's less buggy
https://twitter.com/dan_abramov/status/1060216917493981184
Ran the bundler locally as a sanity check

Switch to Terser

---

docs/hyperscript.md

Added an anchor to the link
Unresponsive link

adding missing anchor link in menu 

---

README.md

READ ME FILE CHANGE
npm installation for local and global wise
It helps newbie to install properly our pacakge
Nothing to check

readme updated for npm installation

---

docs/change-log.md
docs/request.md

Fix #1908, document fields.

---

bundler/cli.js
bundler/tests/test-bundler.js
package-lock.json
package.json
render/render.js

~~Having two exports is pretty redundant - you're only saving 2 non-whitespace characters by using a default export. Also, I fixed some linter issues I ran into.~~ **Edit:** Noticed that our local ESLint version was outdated and that there were a few odd things missed. I also ran `npm audit fix` as a drive-by.
Saving the module changes for later once I have some bundler support.

Fix some linter issues, update ESLint

---

.travis.yml

Added `npm run build-esm` to travis config in order to for Gandalf-bot to automatically generate/commit `mithril.mjs` and `mithril.min.mjs` (fixes #2325)
Current esm build on next branch is out of date and not being automatically built.
Untested

make gandalf run build-esm fixes #2325

---

esm.js

Updated the export variable name in `esm.js` to properly reflect the current variable name in `stream.js`
fixes #2329
The current `stream.mjs` on the next branch is referring to an undefined variable `createStream` and does not work.
Hand tested

update stream export name (esm build)

---

docs/route.md

Show how to use each routing strategy in docs

---

README.md
docs/index.md
docs/installation.md
docs/nav-guides.md
docs/releasing.md
docs/stream.md

This should help point users to the correct version if they plan to
install the release candidate, and it should help users find the
existing docs for v1.
Fixes #2358

s/mithril/mithril@next/g, add v1 docs link [skip ci]

---

examples/editor/index.html
ospec/change-log.md
ospec/package.json
package-lock.json
package.json

Ran `npm outdated` and resolved its issues. I also updated ospec's changelog, and I plan to release `ospec@3.1.0` with this immediately after it gets merged.
This PR is purely just a smoke test - there's nothing to review here.
We had some seriously outdated dependencies and `npm audit` wouldn't shut up. It will now that I'm updating the relevant dev dependency by a couple major versions (`gh-pages` from `0.12.0` to `2.0.1`). 😉

Update a few dependencies, update ospec to version 3.1.0

---

docs/stream.md

Small typo fix

---

api/router.js
api/tests/test-router.js
docs/route.md
stream/tests/test-scan.js

- Added `route` param in `onmatch`, which contains url excluding interpolated routing parameter values
- `route` param was already being passed to resolve method in `defineRoutes`, just was not consumed by resolve function
- Need url defined by the user to use in analytics. `path` contains interpolated routing parameter values making it difficult to group together similar paths for analytics.
- Added using test
- [Demo](https://flems.io/#0=N4IgZglgNgpgziAXAbVAOwIYFsZJAOgAsAXLKEAGhAGMB7NYmBvEAXwvW10RCwmMIAnaPgBWCKnQZNieAIRgArmmrEI9ABQBKYAB0QiuDAAEcYsNX6A3EpVr6xmBpgViFNBUEVaFCDsEwxIqCaMDEGADmiC4A1jAAnohuGMTmcIge1ITQACYBaIhejAAexIg+ObRYiBAUlVgAyhAAXjCIAG60EDnGAAwUZiltnd19FDDtMukjPf0QaIMqw12zrKww+Gi0glgYUC0wALy2qupoGsT+gcFoxgCCgoIY8fgQcA9P8RdaAPxO+sh9BQZmMQf0NlsdnsDgBhbJQPJMb7Alag1G9LQZRRQKByQ …

Feature onmatch route param

---

README.md
docs/contributing.md
docs/index.md

We have decided to start accepting donations to the project. We don't actively solicit for them, but we *do* accept them.
This PR adds a simple badge so others know we accept donations.
@barneycarroll @StephanHoyer Is this sufficient? I wanted to run it by you all first. I'm also not the most fond of the label, but I can't really think of anything better.

Mithril now accepts donations through OpenCollective

---

examples/threaditjs/index.html

Mixed Content: The page at 'https://cdn.rawgit.com/MithrilJS/mithril.js/master/examples/threaditjs/index.html' was loaded over HTTPS, but requested an insecure stylesheet 'http://threaditjs.com/reset.css'. This request has been blocked; the content must be served over HTTPS.
Mixed Content: The page at 'https://cdn.rawgit.com/MithrilJS/mithril.js/master/examples/threaditjs/index.html'
- [ x] Bug fix (non-breaking change which fixes an issue)
- [x ] Documentation change
- [ x] My code follows the code style of this project.
- [ x] I have read the **CONTRIBUTING** document.
- [x ] All new and existing tests passed.

Fix mixed content error.

---

docs/route.md

m.route.params() -> m.route.param()

fix small typo

---

docs/style.css

Added a font-family : sans-serif to improve the backward compatibility.
This changed is required in case the primary fonts are not being loaded like if Google Fonts are blocked on a particular system.
**Issue Link** : https://github.com/MithrilJS/mithril.js/issues/2407

Adding fallback font-family sans-serif

---

docs/request.md

Split params and body, as making a PUT request with no body and a query string is atypical.
Refs https://github.com/MithrilJS/mithril.js/pull/2425#discussion_r292199241
Viewed Markdown preview.

Improve initial request docs example

---

docs/framework-comparison.md
docs/index.md

Thank you all these freaking edge cases and perf bugs... :-(
Ran `npm run build-min` and compared the output.

Mithril's grown a bit

---

docs/paths.md

Nobody has asked yet explicitly, but I'd like to not form assumptions about the reader. Also, it's come up on rare occasion a while back, on both GitHub and Gitter.
N/A - it's just a docs update

Clarify need for escaping, to avoid confusion

---

render/render.js
render/tests/test-normalizeChildren.js
render/vnode.js

Should result in more informative stack traces. It now throws from inside the view rather than from inside Mithril's renderer.
Fixes #2461
Updated tests, actually tested the check itself.

Move fragment type check to normalizer

---

api/router.js
api/tests/test-router.js
docs/route.md
docs/signatures.md

Change `component:` to `selector:` in `m.route.Link`
Minor design bug, one I'd like to catch and fix *before* v2 goes stable. See https://github.com/MithrilJS/mithril.js/pull/2469#issuecomment-511168469 for rationale. (Thanks, @spacejack!)
Updated the tests accordingly

Fix design bug

---

api/router.js
api/tests/test-router.js
docs/keys.md
docs/route.md
render/tests/test-event.js
test-utils/domMock.js

- Fix a copy/paste fail when creating `m.route.Link`. (It was *baaaaaaaaaaddddddd*.)
- Fix tests to actually test that code path.
- Fix event tests to test for observable propagation, not an internal constant.
- Document intended semantics for route changes. (This has been the case since routing was first added to Mithril in v0.1, but was not documented at all since at least v1 was first released, likely not even v0.2. 😱)
- Fix docs to clarify around how keys work. The initial docs for that single-child keyed fragment pattern were pretty unclear, and there was an "avoid" part that contradicted with it.
- Various edits for consistency.
Fixes #2474 
A half dozen new tests, everything passes locally.

Fix link + docs

---

README.md

Spelling of "JavaScript"

---

docs/migration-v1x.md

In section "Migrating from v1.x": "remvoed" should be "removed"

Fix typo in docs

---

docs/es6.md

The backticks were messing up the rendered documentation at https://mithril.js.org/es6.html

Replace backticks in code example

---

.npmignore
docs/change-log.md

update .npmignore so that archives are not included in the resulting package
- space/bandwidth savings
- fix #2552
- I am not sure how to test it (I guess the directory is only present on the CI/CD machine)
- it changes only the resulting bundle and removes unnecessary directory

Exclude archive of previous docs

---

docs/learning-mithril.md

The scrimba version of Mithril 0-60 was built on their beta platform, and doesn't really even work anymore. These Vimeo screencasts are more up-to-date and generally better.

updated to the Vimeo showcase

---

docs/testing.md

Fixed a typo in testing doc page.
Currently there is reference to `mocha` in the page whereas `opsec` is used.

Replace mocha by ospec in testing page

---

docs/simple-application.md

When following tutorial and typing everything in, I was confused that Save button didn't work. Turned out that tutorial switches type from "button" to "submit", which I haven't spotted. Perhaps it should had been "submit" from start?

simple-application.md: consistent use of type=submit

---

docs/route.md

Cavemansspa patch 1

---

docs/installation.md

Content was moved some time ago and linked section no longer exists.

Remove old TOC link

---

docs/route.md

Also fixes a broken internal link

Document route resolution cancellation, fixes #1759

---

docs/jsx.md

As a developer I tried setting up Mithril with Babel and Webpack but failed because of a variety of errors. After some research I have adjusted the documentation so that works with the latest versions.
Following the documentation does not lead to a working environment based on the latest versions. The guide needs to provide a working set of instructions.
The updated instructions have been run in a clean environment and tested on a small Mithril/JSX codebase.
Babel 7.12.10
Webpack 5.11.1
Mithril 2.0.4

Updated babel/webpack docs to work with latest versions

---

docs/changelog.md
index.js

The title says it all, and the diff's obvious.
Resolves https://github.com/MithrilJS/mithril.js/issues/2640 and probably others
N/A - there isn't really anything here to test specifically other than making sure it's syntactically correct.

Add a `m.Fragment = "["` utility for JSX users.

---

README.md

- use consistent naming of Mithril.js
- fix badges in README
Fixes issue #2749

Fixed badges, consistent naming of Mithril.js

---

docs/installation.md

Make example work with webpack v5.69.1

---

.github/workflows/merge.yml
.github/workflows/pr.yml
.github/workflows/rollback.yml

https://github.com/MithrilJS/mithril.js/runs/6199543939?check_suite_focus=true

Fix branch target

---

README.md
docs/layout.html
docs/simple-application.md
docs/support.md

This updates the links to the new chat. Please don't merge, I'll do it once the Zulip instance is finalized.
Also, I don't remember how we publish to mithril.js.org...

Move the chat to Zulip

---

README.md
docs/layout.html
docs/simple-application.md
docs/support.md

- #2771
This updates the documentation to link to the new Zulip chat room.

Release - v2.2.1

---

README.md

- #2773
Use markdown for the README badges.

Release - v2.2.2

---

.github/workflows/lint-docs.yml
.github/workflows/lint-js.yml
.github/workflows/test-js.yml
docs/jsx.md
docs/request.md
package-lock.json
package.json

Enable CI that was I suppose disabled by mistake.

Add back CI

---

render/domFor.js

The `domFor` patch breaks the compiled output: the bundler can't handle multiple exports per module.
1. [Compiled code sandbox: before](https://flems.io/#0=N4IgtglgJlA2CmIBcBGADGgNCAzvBAxgC7xTIgAWRRADjkgPQMCuAdjQNYDmAdAQPZgGkIhQBOEWAAEATDzkzhEURNg8AVjhDYAZpPhakAbQC62WBFYdDR0KwCGYREnDLxkjVuzMxsclVp6JjZOXgEhEXdpBXklFQ9NbRAiAE8aZ1wCCRoiJJp7IgIKA2QjMqwQGQAdVgBfGpAzIwBaFGwGACoAAi5YfgAje1gugHdLKH4Rro6GGs7uqQFWHCIxZmJ+MWnZ1gA3ey2ABTFBCDxD-lgUvVhhgF4unTZiCH5WAAp4AA94AmYiTYASi6wBqVSIEB0XXeAEJ3qIzl1LCt7KwCPB+FDjqdzpdrpJYIDgSpJl1WPApgBRMQnMTvKogbGQPBdMDMFZdfrwLoEIYIKCjNxdADk5JGwp4DMBYIhUPhaQxUO+v3+my6MLuDwZTzRELeUq6JKmYq6ABUFdTafSQMq-gCtmyOVyuvZHs89axJSBpaxwfstnhYFCHgicJgumIDJddvAxDgug9TOHI+pfvb44mzBGo7AYwBhHyR1hEBNdCiouCx96RnDR2Nhw1reCA5PwVPEAs0+DF0vl1iVukptObBs6IZ4H1+g5I5ZEVHo0uBnQ8AD6yLnaO5D2ANbrc …

Fix silent build error in next: bundler can't handle multiple exports per module

---

.github/CODEOWNERS

Most collaborators have commit access, and it'd make it a little easier (and more likely) for pull requests to get reviewed. Also, most collaborators have merge access as well.

Move from individual code owners to just pinging all collaborators

---

README.md

The URL for the Shields.io badge for build status has been corrected.
I noticed that the build status badge is showing "repo or workflow not found" even though the test passed and the build is working properly.
I found out that this was due to the workflow yml being integrated.
https://github.com/MithrilJS/mithril.js/commit/08f5ccfedacf78fe24c1dc522b0f1af7fb846558
I have checked that the badge on the revised URL can show the current, presumably correct status.

Fix badge for build status
